/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layer_Presentation;

import Layer_Business.LB_BranchOffice;
import Layer_Business.LB_Canton;
import Layer_Business.LB_Country;
import Layer_Business.LB_District;
import Layer_Business.LB_KeyEvent;
import Layer_Business.LB_Person;
import Layer_Business.LB_Profile;
import Layer_Business.LB_Province;
import Layer_Business.LB_User;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author KGR
 */
public class JDAddUser extends javax.swing.JDialog {

    /**
     * Creates new form JDAddUser
     */
    LB_User LB = new LB_User();
    LB_Country LBC = new LB_Country();
    LB_Province LBPC = new LB_Province();
    LB_Canton LBCT = new LB_Canton();
    LB_District LBD = new LB_District();
    LB_Profile LBP = new LB_Profile();
    LB_Person LBPE = new LB_Person();
    LB_BranchOffice LBBO = new LB_BranchOffice();
    LB_KeyEvent LBKE = new LB_KeyEvent();
    
    
    public JDAddUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        ListProfile();
        ListCountry();
        ListBranchOffice();
    }
    
     public void ListProfile()
    {
        try 
        {
            LBP.ListProfile(this.jComboBox_Profile);
        }
        catch (Exception ex) 
        {
            System.out.println(ex.getMessage());
        }
        
    }
     public void ListBranchOffice()
    {
        try 
        {
            LBBO.ListBranchOfficeCBO(this.jComboBox_BranchOffice);
        }
        catch (Exception ex) 
        {
            System.out.println(ex.getMessage());
        }
        
    }
     
    public void GetDataBranchOffice()
    {
        LB_BranchOffice Office =  (LB_BranchOffice) this.jComboBox_BranchOffice.getSelectedItem();
        String idO = Office.getID_BranchOffice();
        this.jLabel_BranchOffice.setText(idO);
    }
     
    public void GetDataProfile()
    {
        LB_Profile profile =  (LB_Profile) this.jComboBox_Profile.getSelectedItem();
        String idC = profile.getID_Profile();
        this.jLabel_Profile.setText(idC);
    }
     
    public void ListCountry()
    {
        try 
        {
            LBC.ListCountry(this.jComboBox_CountryPeron);
        }
        catch (Exception ex) 
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void GetDataCountry()
    {
        LB_Country country =  (LB_Country) this.jComboBox_CountryPeron.getSelectedItem();
        String idC = country.getID_Country();
        this.jLabel_Country.setText(idC);
        
        /*PROVINCE*/
        LBPC.setID_Country(idC);
        LBPC.ListProvince(jComboBox_ProvincePerson);
    }
    
    public void GetDataProvince()
    {
        LB_Province province =  (LB_Province) this.jComboBox_ProvincePerson.getSelectedItem();
        String idP = province.getID_Province();
        this.jLabel_Province.setText(idP);
      
        /*DISTRICT*/
        LBD.setID_Province(idP);
        LBD.ListDistrict(jComboBox_DistrictPerson);
    }
    
    
    public void GetDataDistrict()
    {
        LB_District district =  (LB_District) this.jComboBox_DistrictPerson.getSelectedItem();
        String idDT = district.getID_District();
        this.jLabel_District.setText(idDT);
        
        /*CANTON*/
        LBCT.setID_District(idDT);
        LBCT.ListCanton(jComboBox_CantonPerson);
        
    }
    
    public void GetDataCanton()
    {
        LB_Canton canton =  (LB_Canton) this.jComboBox_CantonPerson.getSelectedItem();
        String idCT = canton.getID_Canton();
        this.jLabel_Canton.setText(idCT);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Profile = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextField_NamePerson = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextField_SurnamePerson = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel_Profile = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField_LastnamePerson = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_GenderPerson = new javax.swing.JComboBox<>();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jDateChooser_BirthdayPerson = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        jComboBox_CountryPeron = new javax.swing.JComboBox<>();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jComboBox_IdentificationTypePerson = new javax.swing.JComboBox<>();
        jLabel_Country = new javax.swing.JLabel();
        jComboBox_ProvincePerson = new javax.swing.JComboBox<>();
        jLabel_Province = new javax.swing.JLabel();
        jComboBox_DistrictPerson = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel_District = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jComboBox_CivilStatusPerson = new javax.swing.JComboBox<>();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jTextField_CellPhonePerson = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jTextField_HomeAddressPerson = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jComboBox_StatePerson = new javax.swing.JComboBox<>();
        jSeparator28 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        jTextField_IdentificationPerson = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jComboBox_CantonPerson = new javax.swing.JComboBox<>();
        jLabel_Canton = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton_SignIn = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jComboBox_BranchOffice = new javax.swing.JComboBox<>();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel_BranchOffice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AA Control - Login");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Sidebar.setBackground(new java.awt.Color(38, 45, 53));
        jPanel_Sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseDragged(evt);
            }
        });
        jPanel_Sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO ");
        jLabel1.setToolTipText("");

        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancel.png"))); // NOI18N
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_SidebarLayout = new javax.swing.GroupLayout(jPanel_Sidebar);
        jPanel_Sidebar.setLayout(jPanel_SidebarLayout);
        jPanel_SidebarLayout.setHorizontalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(280, 280, 280)
                .addComponent(jLabel_Close)
                .addContainerGap())
        );
        jPanel_SidebarLayout.setVerticalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 40));

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));

        jTabbedPane3.setBackground(new java.awt.Color(240, 240, 240));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(119, 123, 125));
        jLabel2.setText("USUARIO - EMAIL");

        jTextField_Email.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_Email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_Email.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_Email.setBorder(null);
        jTextField_Email.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_EmailKeyTyped(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(38, 45, 53));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(119, 123, 125));
        jLabel3.setText("CONTRASEÑA");

        jPasswordField_Password.setBackground(new java.awt.Color(240, 240, 240));
        jPasswordField_Password.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPasswordField_Password.setForeground(new java.awt.Color(105, 105, 105));
        jPasswordField_Password.setBorder(null);
        jPasswordField_Password.setMaximumSize(new java.awt.Dimension(0, 19));
        jPasswordField_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_PasswordKeyTyped(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(38, 45, 53));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(119, 123, 125));
        jLabel4.setText("PERFIL");

        jComboBox_Profile.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_Profile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_Profile.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_Profile.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ProfileItemStateChanged(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(38, 45, 53));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(119, 123, 125));
        jLabel6.setText("NOMBRE");

        jTextField_NamePerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_NamePerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_NamePerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_NamePerson.setBorder(null);
        jTextField_NamePerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_NamePerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NamePersonKeyTyped(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(38, 45, 53));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(119, 123, 125));
        jLabel7.setText("PRIMER APELLIDO");

        jTextField_SurnamePerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_SurnamePerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_SurnamePerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_SurnamePerson.setBorder(null);
        jTextField_SurnamePerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_SurnamePerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_SurnamePersonKeyTyped(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(38, 45, 53));

        jLabel_Profile.setText("ID");

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(119, 123, 125));
        jLabel24.setText("SEGUNDO APELLIDO");

        jTextField_LastnamePerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_LastnamePerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_LastnamePerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_LastnamePerson.setBorder(null);
        jTextField_LastnamePerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_LastnamePerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_LastnamePersonKeyTyped(evt);
            }
        });

        jSeparator23.setBackground(new java.awt.Color(38, 45, 53));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_Profile, javax.swing.GroupLayout.Alignment.LEADING, 0, 211, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField_Password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5)
                                .addComponent(jTextField_NamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator6)
                                .addComponent(jTextField_SurnamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_LastnamePerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel_Profile))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_NamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_SurnamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_LastnamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Profile)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Pág 1", jPanel3);

        jPanel4.setBackground(new java.awt.Color(240, 240, 240));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(119, 123, 125));
        jLabel10.setText("TIPO IDENTIFICACIÓN");

        jSeparator9.setBackground(new java.awt.Color(38, 45, 53));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(119, 123, 125));
        jLabel11.setText("GÉNERO");

        jComboBox_GenderPerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_GenderPerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_GenderPerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_GenderPerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));

        jSeparator10.setBackground(new java.awt.Color(38, 45, 53));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(119, 123, 125));
        jLabel12.setText("FECHA CUMPLEAÑOS");

        jSeparator11.setBackground(new java.awt.Color(38, 45, 53));

        jDateChooser_BirthdayPerson.setBackground(new java.awt.Color(240, 240, 240));
        jDateChooser_BirthdayPerson.setForeground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(119, 123, 125));
        jLabel25.setText("PAIS");

        jComboBox_CountryPeron.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_CountryPeron.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_CountryPeron.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_CountryPeron.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_CountryPeronItemStateChanged(evt);
            }
        });

        jSeparator24.setBackground(new java.awt.Color(38, 45, 53));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(119, 123, 125));
        jLabel20.setText("PROVINCIA");

        jSeparator19.setBackground(new java.awt.Color(38, 45, 53));

        jSeparator26.setBackground(new java.awt.Color(38, 45, 53));

        jComboBox_IdentificationTypePerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_IdentificationTypePerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_IdentificationTypePerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_IdentificationTypePerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula", "Pasaporte", "Carné Residencia" }));

        jLabel_Country.setText("ID");

        jComboBox_ProvincePerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_ProvincePerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_ProvincePerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_ProvincePerson.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ProvincePersonItemStateChanged(evt);
            }
        });

        jLabel_Province.setText("ID");

        jComboBox_DistrictPerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_DistrictPerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_DistrictPerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_DistrictPerson.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_DistrictPersonItemStateChanged(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(119, 123, 125));
        jLabel19.setText("DISTRITO");

        jLabel_District.setText("ID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jComboBox_GenderPerson, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jComboBox_CountryPeron, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addComponent(jSeparator24, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jComboBox_IdentificationTypePerson, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel_Country))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel_Province)
                        .addComponent(jLabel20)
                        .addComponent(jComboBox_ProvincePerson, 0, 217, Short.MAX_VALUE)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator26)
                        .addComponent(jSeparator11)
                        .addComponent(jLabel12)
                        .addComponent(jDateChooser_BirthdayPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel19)
                    .addComponent(jComboBox_DistrictPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_District))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_IdentificationTypePerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel20))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_GenderPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_ProvincePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_BirthdayPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_Province)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_CountryPeron, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_DistrictPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Country)
                    .addComponent(jLabel_District))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Pág 2", jPanel4);

        jPanel5.setBackground(new java.awt.Color(240, 240, 240));

        jSeparator16.setBackground(new java.awt.Color(38, 45, 53));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(119, 123, 125));
        jLabel18.setText("ESTADO FAMILIAR");

        jComboBox_CivilStatusPerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_CivilStatusPerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_CivilStatusPerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_CivilStatusPerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado", "Viudo", "Separacion", "Union_Libre", "Otro" }));

        jSeparator17.setBackground(new java.awt.Color(38, 45, 53));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(119, 123, 125));
        jLabel26.setText("TELÉFONO MÓVIL");

        jTextField_CellPhonePerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_CellPhonePerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_CellPhonePerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_CellPhonePerson.setBorder(null);
        jTextField_CellPhonePerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_CellPhonePerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CellPhonePersonKeyTyped(evt);
            }
        });

        jSeparator25.setBackground(new java.awt.Color(38, 45, 53));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(119, 123, 125));
        jLabel28.setText("DIRECCIÓN CASA");

        jTextField_HomeAddressPerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_HomeAddressPerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_HomeAddressPerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_HomeAddressPerson.setBorder(null);
        jTextField_HomeAddressPerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_HomeAddressPerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_HomeAddressPersonKeyTyped(evt);
            }
        });

        jSeparator27.setBackground(new java.awt.Color(38, 45, 53));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(119, 123, 125));
        jLabel29.setText("ESTADO");

        jComboBox_StatePerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_StatePerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_StatePerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_StatePerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Inhabilitado" }));

        jSeparator28.setBackground(new java.awt.Color(38, 45, 53));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(119, 123, 125));
        jLabel30.setText("IDENTIFICACIÓN");

        jSeparator29.setBackground(new java.awt.Color(38, 45, 53));

        jTextField_IdentificationPerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_IdentificationPerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_IdentificationPerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_IdentificationPerson.setBorder(null);
        jTextField_IdentificationPerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_IdentificationPerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IdentificationPersonKeyTyped(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(119, 123, 125));
        jLabel27.setText("CANTON");

        jComboBox_CantonPerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_CantonPerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_CantonPerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_CantonPerson.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_CantonPersonItemStateChanged(evt);
            }
        });

        jLabel_Canton.setText("ID");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26)
                            .addComponent(jTextField_CellPhonePerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator25, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jSeparator16, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jComboBox_CivilStatusPerson, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18)
                            .addComponent(jSeparator17, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel27)
                            .addComponent(jComboBox_CantonPerson, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_IdentificationPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBox_StatePerson, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel30)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_HomeAddressPerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_Canton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_HomeAddressPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_CantonPerson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(31, 31, 31)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Canton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(4, 4, 4)
                                .addComponent(jComboBox_CivilStatusPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_CellPhonePerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(4, 4, 4)
                                .addComponent(jComboBox_StatePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_IdentificationPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        jTabbedPane3.addTab("Pág 3", jPanel5);

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));

        jButton_SignIn.setBackground(new java.awt.Color(214, 61, 92));
        jButton_SignIn.setForeground(new java.awt.Color(255, 255, 255));
        jButton_SignIn.setText("Registrar");
        jButton_SignIn.setToolTipText("");
        jButton_SignIn.setBorder(null);
        jButton_SignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_SignIn.setFocusable(false);
        jButton_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SignInActionPerformed(evt);
            }
        });

        jButton_Cancel.setBackground(new java.awt.Color(214, 61, 92));
        jButton_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cancel.setText("Cancelar");
        jButton_Cancel.setToolTipText("");
        jButton_Cancel.setBorder(null);
        jButton_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Cancel.setFocusable(false);
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(119, 123, 125));
        jLabel31.setText("SEDE/SUCURSAL");

        jComboBox_BranchOffice.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_BranchOffice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_BranchOffice.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_BranchOffice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_BranchOfficeItemStateChanged(evt);
            }
        });

        jSeparator18.setBackground(new java.awt.Color(38, 45, 53));

        jLabel_BranchOffice.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel31)
                            .addComponent(jLabel_BranchOffice)
                            .addComponent(jSeparator18)
                            .addComponent(jComboBox_BranchOffice, 0, 367, Short.MAX_VALUE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_BranchOffice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(31, 31, 31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_BranchOffice)
                .addGap(138, 138, 138)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Pág 4", jPanel1);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icono-cliente.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(63, 63, 63))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel5)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 660, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jTextField_EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EmailKeyTyped
        // TODO add your handling code here:
        LBKE.NumbersAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_EmailKeyTyped

    private void jButton_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SignInActionPerformed
        // TODO add your handling code here:

        if (!jTextField_Email.getText().isEmpty())
        {
            if (!jPasswordField_Password.getText().isEmpty())
            {
                if (!jTextField_NamePerson.getText().isEmpty())
                {
                    if (!jTextField_SurnamePerson.getText().isEmpty())
                    {
                        if (!jTextField_LastnamePerson.getText().isEmpty())
                        {
                            if (!jTextField_IdentificationPerson.getText().isEmpty())
                            {
                                if (jDateChooser_BirthdayPerson.getCalendar() != null) 
                                {
                                    if (jComboBox_ProvincePerson.getSelectedIndex() >= 0)
                                    {
                                        if (jComboBox_CantonPerson.getSelectedIndex() >= 0)
                                        {
                                            if (jComboBox_DistrictPerson.getSelectedIndex() >= 0)
                                            {
                                                if (!jTextField_CellPhonePerson.getText().isEmpty())
                                                {
                                                    if (!jTextField_HomeAddressPerson.getText().isEmpty())
                                                        {
                                                            String Pass = jPasswordField_Password.getText();
                                                            String Profile = jComboBox_Profile.getSelectedItem().toString();
                                                            //String IDPerson = jTextField_IDPerson.getText();
                                                            String Name = jTextField_NamePerson.getText();
                                                            String Surname = jTextField_SurnamePerson.getText();
                                                            String Lastname = jTextField_LastnamePerson.getText();
                                                            String IdentificationType = jComboBox_IdentificationTypePerson.getSelectedItem().toString();
                                                            String Identificacion = jTextField_IdentificationPerson.getText();
                                                            String Gender = jComboBox_GenderPerson.getSelectedItem().toString();

                                                            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                                                            String Birthday = dateFormat.format(jDateChooser_BirthdayPerson.getDate());

                                                            //String Country = jComboBox_CountryPeron.getSelectedItem().toString();
                                                            LB_Country country =  (LB_Country) this.jComboBox_CountryPeron.getSelectedItem();
                                                            String idCountry = country.getID_Country();
                                                            
                                                            //String Province = jComboBox_ProvincePerson.getSelectedItem().toString();
                                                            LB_Province province =  (LB_Province) this.jComboBox_ProvincePerson.getSelectedItem();
                                                            String idProvince = province.getID_Province();
                                                            
                                                            //String Canton = jComboBox_CantonPerson.getSelectedItem().toString();
                                                            LB_District district =  (LB_District) this.jComboBox_DistrictPerson.getSelectedItem();
                                                            String idDistrict = district.getID_District();
                                                            
                                                            //String District = jComboBox_DistrictPerson.getSelectedItem().toString();
                                                            LB_Canton canton =  (LB_Canton) this.jComboBox_CantonPerson.getSelectedItem();
                                                            String idCanton = canton.getID_Canton();
                                                            
                                                            String CivilStatus = jComboBox_CivilStatusPerson.getSelectedItem().toString();
                                                            String CellPhone = jTextField_CellPhonePerson.getText();
                                                            String Email = jTextField_Email.getText();
                                                            String HomeAddress = jTextField_HomeAddressPerson.getText();
                                                            String State = jComboBox_StatePerson.getSelectedItem().toString();

                                                            //SAVE
                                                            GetDataProfile();
                                                            String complement = "PERS_"+Identificacion;
//                                                            Random random = new Random();
//                                                            int N1 = random.nextInt(1000);
//                                                            int N2 = random.nextInt(500);
//                                                            int N3 = random.nextInt(300);
//                                                            int N4 = random.nextInt(100);
//                                                            String Complement = "PER";
//                                                            String IDPerson =  Complement + N1 + N2 + N3 + N4;

                                                            LB_Profile profile =  (LB_Profile) this.jComboBox_Profile.getSelectedItem();
                                                            String id_Profile = profile.getID_Profile();
                                                            
                                                            LB_BranchOffice Office =  (LB_BranchOffice) this.jComboBox_BranchOffice.getSelectedItem();
                                                            String idO = Office.getID_BranchOffice();
                                                            
                                                            LB = new LB_User(complement, Pass, id_Profile);
                                                            
                                                            LBPE = new LB_Person(complement, Name, Surname,
                                                                    Lastname, IdentificationType, 
                                                                    Identificacion, Gender, Birthday,
                                                                    idCountry, idProvince, idDistrict, idCanton, idO,
                                                                     CivilStatus, CellPhone, 
                                                                    Email, HomeAddress, State);

                                                            //Insert Person
                                                            String rptaRegistro = LBPE.Insert();

                                                            //Insert the User
                                                            String  rptaRegistro1 = LB.InsertUser(id_Profile);

                                                            if (rptaRegistro != null) 
                                                            {
                                                                JOptionPane.showMessageDialog(null, "Person " + complement + "\n" + rptaRegistro, "AA Control - SignIn", JOptionPane.INFORMATION_MESSAGE);
                                                                //listar
                                                            }
                                                      
                                                            if(rptaRegistro1 != null)
                                                            {
                                                                JOptionPane.showMessageDialog(null, "User " + "\n" + LB.IDPerson + " " + rptaRegistro1, "AA Control - SignIn", JOptionPane.INFORMATION_MESSAGE);
                                                                JOptionPane.showMessageDialog(null, "AA Control will close, you can log in with the credentials that you chose during registration", 
                                                                  "AA Control - SignIn", JOptionPane.INFORMATION_MESSAGE);
                                                                System.exit(0);
                                                            }
                                                        }
                                                        else
                                                        {
                                                            JOptionPane.showMessageDialog(null, "The HomeAddress Is Required !", "AA Control - SignIn", JOptionPane.WARNING_MESSAGE);
                                                        }
                                                }
                                                else
                                                {
                                                    JOptionPane.showMessageDialog(null, "The CellPhone Is Required !", "AA Control - SignIn", JOptionPane.WARNING_MESSAGE);
                                                }
                                            }
                                            else
                                            {
                                                JOptionPane.showMessageDialog(null, "The District Is Required !", "AA Control - SignIn", JOptionPane.WARNING_MESSAGE);
                                            }
                                        }
                                        else
                                        {
                                            JOptionPane.showMessageDialog(null, "The Canton Is Required !", "AA Control - SignIn", JOptionPane.WARNING_MESSAGE);
                                        }
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(null, "The Province Is Required !", "AA Control - SignIn", JOptionPane.WARNING_MESSAGE);
                                    }
                                  
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "The Birthday Is Required !", "AA Control - SignIn", JOptionPane.WARNING_MESSAGE);
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null, "The Identification Is Required !", "AA Control - SignIn", JOptionPane.WARNING_MESSAGE);
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "The Lastname Is Required !", "AA Control - SignIn", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "The Surname Is Required !", "AA Control - SignIn", JOptionPane.WARNING_MESSAGE);
                    }
                }
                else 
                {
                    JOptionPane.showMessageDialog(null, "The Name Is Required !", "AA Control - SignIn", JOptionPane.WARNING_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "The password Is Required !", "AA Control - SignIn", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "The User Is Required !", "AA Control - SignIn", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton_SignInActionPerformed

    private void jTextField_NamePersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NamePersonKeyTyped
        // TODO add your handling code here:
        LBKE.CharactersMayusAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_NamePersonKeyTyped

    private void jTextField_SurnamePersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SurnamePersonKeyTyped
        // TODO add your handling code here:
        LBKE.CharactersMayusAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_SurnamePersonKeyTyped

    private void jComboBox_ProfileItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ProfileItemStateChanged
        // TODO add your handling code here:
        GetDataProfile();
    }//GEN-LAST:event_jComboBox_ProfileItemStateChanged

    private void jTextField_LastnamePersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_LastnamePersonKeyTyped
        // TODO add your handling code here:
        LBKE.CharactersMayusAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_LastnamePersonKeyTyped

    private void jTextField_CellPhonePersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CellPhonePersonKeyTyped
        // TODO add your handling code here:
        LBKE.Numbers(evt);
    }//GEN-LAST:event_jTextField_CellPhonePersonKeyTyped

    private void jPasswordField_PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordKeyTyped
        // TODO add your handling code here:
        LBKE.NumbersAndCharactersMinAndCharactersMayus(evt);
    }//GEN-LAST:event_jPasswordField_PasswordKeyTyped

    private void jTextField_HomeAddressPersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_HomeAddressPersonKeyTyped
        // TODO add your handling code here:
        LBKE.CharactersMayusAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_HomeAddressPersonKeyTyped

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        int rptaCategory = JOptionPane.showConfirmDialog(null, 
                "Would you like to Exit ? \n If you Continue, "
                + "the registration will be canceled", 
                "AA Control - Register",JOptionPane.YES_NO_CANCEL_OPTION);
        //si la respuesta es si el valor de rptaUsuario será 1, no -> 2, cancelar -> 3
        if (rptaCategory == 0) 
        {
            //System.exit(0);
            this.dispose();
        }
    }//GEN-LAST:event_jButton_CancelActionPerformed

    int xy, xx;
    private void jPanel_SidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel_SidebarMouseDragged

    private void jPanel_SidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel_SidebarMousePressed

    private void jPanel_SidebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_jPanel_SidebarMouseReleased

    private void jTextField_IdentificationPersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IdentificationPersonKeyTyped
        // TODO add your handling code here:
        LBKE.NumbersAndCharactersMayus(evt);
    }//GEN-LAST:event_jTextField_IdentificationPersonKeyTyped

    private void jComboBox_CountryPeronItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_CountryPeronItemStateChanged
        // TODO add your handling code here:
        GetDataCountry();
    }//GEN-LAST:event_jComboBox_CountryPeronItemStateChanged

    private void jComboBox_ProvincePersonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ProvincePersonItemStateChanged
        // TODO add your handling code here:
        GetDataProvince();
    }//GEN-LAST:event_jComboBox_ProvincePersonItemStateChanged

    private void jComboBox_DistrictPersonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_DistrictPersonItemStateChanged
        // TODO add your handling code here:
        GetDataDistrict();
    }//GEN-LAST:event_jComboBox_DistrictPersonItemStateChanged

    private void jComboBox_CantonPersonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_CantonPersonItemStateChanged
        // TODO add your handling code here:
        GetDataCanton();
    }//GEN-LAST:event_jComboBox_CantonPersonItemStateChanged

    private void jComboBox_BranchOfficeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_BranchOfficeItemStateChanged
        // TODO add your handling code here:
        GetDataBranchOffice();
    }//GEN-LAST:event_jComboBox_BranchOfficeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAddUser dialog = new JDAddUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Cancel;
    public javax.swing.JButton jButton_SignIn;
    private javax.swing.JComboBox<String> jComboBox_BranchOffice;
    private javax.swing.JComboBox<String> jComboBox_CantonPerson;
    private javax.swing.JComboBox<String> jComboBox_CivilStatusPerson;
    private javax.swing.JComboBox<String> jComboBox_CountryPeron;
    private javax.swing.JComboBox<String> jComboBox_DistrictPerson;
    private javax.swing.JComboBox<String> jComboBox_GenderPerson;
    private javax.swing.JComboBox<String> jComboBox_IdentificationTypePerson;
    private javax.swing.JComboBox<String> jComboBox_Profile;
    private javax.swing.JComboBox<String> jComboBox_ProvincePerson;
    private javax.swing.JComboBox<String> jComboBox_StatePerson;
    private com.toedter.calendar.JDateChooser jDateChooser_BirthdayPerson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_BranchOffice;
    private javax.swing.JLabel jLabel_Canton;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_Country;
    private javax.swing.JLabel jLabel_District;
    private javax.swing.JLabel jLabel_Profile;
    private javax.swing.JLabel jLabel_Province;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_Sidebar;
    public javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JTextField jTextField_CellPhonePerson;
    public javax.swing.JTextField jTextField_Email;
    public javax.swing.JTextField jTextField_HomeAddressPerson;
    public javax.swing.JTextField jTextField_IdentificationPerson;
    public javax.swing.JTextField jTextField_LastnamePerson;
    public javax.swing.JTextField jTextField_NamePerson;
    public javax.swing.JTextField jTextField_SurnamePerson;
    // End of variables declaration//GEN-END:variables
}
