/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layer_Presentation;

import Layer_Business.LB_CIF;
import Layer_Business.LB_KeyEvent;
import Layer_Business.LB_Person;
import java.text.SimpleDateFormat;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author KGR
 */
public class JDCIF extends java.awt.Dialog {

    /**
     * Creates new form JDTest
     */
    LB_CIF LB = new LB_CIF();
    LB_KeyEvent LBKE = new LB_KeyEvent();
    public Boolean Actualizar = false;
    String Response;
    public String ID;
    
    public JDCIF(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        ListCIFType();
        ListPerson();
        GetDataPerson();
        ListCIFType1();
        //ListCIF_CIFType();
    }
    
    public void ListPerson()//combobox
    {
        LB.ListPerson(this.jComboBox_IDPersonCIF);
    }
    
     public void ListCIF_CIFType()
    {
        String id = ID;
        LB.ListCIF_CIFType(this.jTable_CIF_CIFType, id);
        
        int numRs = this.jTable_CIF_CIFType.getRowCount();
        if (numRs <4)
        {
            this.jButton_InsertCIFType.setEnabled(true);
        }
        else 
        {
            this.jButton_InsertCIFType.setEnabled(false);
        }
        
        if (numRs >1)
        {
            this.jButton_DeleteCIFType.setEnabled(true);
        }
        else 
        {
            this.jButton_DeleteCIFType.setEnabled(false);
        }
    }
    
    public void ListCIFType()
    {
        LB.ListCIFType(this.jComboBox_CIFType);
    }
    
     public void GetDataCIFType()
    {
        LB_CIF CIFType =  (LB_CIF) this.jComboBox_CIFType.getSelectedItem();
        String id = CIFType.getID_CIFType();
        this.jLabel_IDCIFType.setText(id);
    }
     
     public void GetDataPerson()
    {
        LB_Person PERSON =  (LB_Person) this.jComboBox_IDPersonCIF.getSelectedItem();
        String idP = PERSON.getID_Person();
        this.jLabel_IDPerson.setText(idP);
    }
     
     public void ListCIFType1()
    {
        LB.ListCIFType(this.jComboBox_CIFType1);
    }
     
     public void GetDataCIFType1()
    {
        LB_CIF CIFType =  (LB_CIF) this.jComboBox_CIFType1.getSelectedItem();
        String id1 = CIFType.getID_CIFType();
        this.jLabel_IDCIFType1.setText(id1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Sidebar = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jComboBox_TypeOfCurrency = new javax.swing.JComboBox<>();
        jSeparator26 = new javax.swing.JSeparator();
        jComboBox_PaymentMethod = new javax.swing.JComboBox<>();
        jComboBox_Denomination = new javax.swing.JComboBox<>();
        jComboBox_CIFType = new javax.swing.JComboBox<>();
        jComboBox_Classification = new javax.swing.JComboBox<>();
        jDateChooser_DateOfAdmission = new com.toedter.calendar.JDateChooser();
        jLabel_IDCIFType = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_Background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_CIF_CIFType = new javax.swing.JTable();
        jButton_InsertCIFType = new javax.swing.JButton();
        jButton_DeleteCIFType = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jComboBox_CIFType1 = new javax.swing.JComboBox<>();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel_IDCIFType1 = new javax.swing.JLabel();
        jButton_ConsultCIFType = new javax.swing.JButton();
        jPanel_BackgroundPrimary = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jTextField_Search = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_IDPersonCIF = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel_IDPerson = new javax.swing.JLabel();
        jLabel_Code = new javax.swing.JLabel();
        jButton_Save = new javax.swing.JButton();
        jLabel_Profile = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Sidebar.setBackground(new java.awt.Color(29, 34, 39));
        jPanel_Sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseDragged(evt);
            }
        });
        jPanel_Sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseReleased(evt);
            }
        });

        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/left_15px.png"))); // NOI18N
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EXPEDIENTE ACADÉMICO  (CIF)");

        javax.swing.GroupLayout jPanel_SidebarLayout = new javax.swing.GroupLayout(jPanel_Sidebar);
        jPanel_Sidebar.setLayout(jPanel_SidebarLayout);
        jPanel_SidebarLayout.setHorizontalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addGap(245, 245, 245)
                .addComponent(jLabel1)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel_SidebarLayout.setVerticalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        add(jPanel_Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 40));

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPane3.setBackground(new java.awt.Color(240, 240, 240));
        jTabbedPane3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(119, 123, 125));
        jLabel6.setText("MODALIDAD COBRO");

        jSeparator5.setBackground(new java.awt.Color(26, 97, 186));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(119, 123, 125));
        jLabel7.setText("DENOMINACIÓN");

        jSeparator6.setBackground(new java.awt.Color(26, 97, 186));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(119, 123, 125));
        jLabel24.setText("FECHA INGRESO");

        jSeparator23.setBackground(new java.awt.Color(26, 97, 186));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(119, 123, 125));
        jLabel14.setText(" TIPO CIF");

        jSeparator13.setBackground(new java.awt.Color(26, 97, 186));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(119, 123, 125));
        jLabel20.setText("CLASIFICACIÓN");

        jSeparator19.setBackground(new java.awt.Color(26, 97, 186));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(119, 123, 125));
        jLabel27.setText("TIPO MONEDA");

        jComboBox_TypeOfCurrency.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_TypeOfCurrency.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_TypeOfCurrency.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_TypeOfCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cordoba_Nicaraguense", "Dolar_Estadounidense", "Dolar_Beliceño", "Colon_Costarricense", "Lempira_Hondureño" }));

        jSeparator26.setBackground(new java.awt.Color(26, 97, 186));

        jComboBox_PaymentMethod.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_PaymentMethod.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_PaymentMethod.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_PaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Extranjero" }));

        jComboBox_Denomination.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_Denomination.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_Denomination.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_Denomination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adventista", "Católico_Romano", "Evangélico", "No_Especificado" }));

        jComboBox_CIFType.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_CIFType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_CIFType.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_CIFType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_CIFTypeItemStateChanged(evt);
            }
        });

        jComboBox_Classification.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_Classification.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_Classification.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_Classification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Externo 1", "Interno 0 Tiempos de Comida", "Interno 1  Tiempos de Comida", "Interno 2  Tiempos de Comida", "Interno 3  Tiempos de Comida" }));

        jDateChooser_DateOfAdmission.setBackground(new java.awt.Color(240, 240, 240));
        jDateChooser_DateOfAdmission.setForeground(new java.awt.Color(105, 105, 105));
        jDateChooser_DateOfAdmission.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel_IDCIFType.setText("ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jSeparator23)
                    .addComponent(jComboBox_PaymentMethod, 0, 211, Short.MAX_VALUE)
                    .addComponent(jComboBox_Denomination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser_DateOfAdmission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14)
                        .addComponent(jSeparator13)
                        .addComponent(jLabel20)
                        .addComponent(jSeparator19)
                        .addComponent(jComboBox_TypeOfCurrency, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addComponent(jSeparator26)
                        .addComponent(jComboBox_CIFType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_Classification, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel_IDCIFType))
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox_PaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_CIFType))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_IDCIFType)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jComboBox_Denomination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox_Classification))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(jLabel27))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox_TypeOfCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser_DateOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Pág 1", jPanel3);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));

        jPanel_Background.setBackground(new java.awt.Color(240, 240, 240));

        jTable_CIF_CIFType.setBackground(new java.awt.Color(240, 240, 240));
        jTable_CIF_CIFType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IDCIF_CIFType", "CIFType"
            }
        ));
        jScrollPane1.setViewportView(jTable_CIF_CIFType);

        jButton_InsertCIFType.setBackground(new java.awt.Color(214, 61, 92));
        jButton_InsertCIFType.setForeground(new java.awt.Color(255, 255, 255));
        jButton_InsertCIFType.setText("Insertar");
        jButton_InsertCIFType.setToolTipText("");
        jButton_InsertCIFType.setBorder(null);
        jButton_InsertCIFType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_InsertCIFType.setFocusable(false);
        jButton_InsertCIFType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertCIFTypeActionPerformed(evt);
            }
        });

        jButton_DeleteCIFType.setBackground(new java.awt.Color(214, 61, 92));
        jButton_DeleteCIFType.setForeground(new java.awt.Color(255, 255, 255));
        jButton_DeleteCIFType.setText("Eliminar");
        jButton_DeleteCIFType.setToolTipText("");
        jButton_DeleteCIFType.setBorder(null);
        jButton_DeleteCIFType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_DeleteCIFType.setFocusable(false);
        jButton_DeleteCIFType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteCIFTypeActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(119, 123, 125));
        jLabel15.setText(" TIPO CIF");

        jComboBox_CIFType1.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_CIFType1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_CIFType1.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_CIFType1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_CIFType1ItemStateChanged(evt);
            }
        });

        jSeparator14.setBackground(new java.awt.Color(26, 97, 186));

        jLabel_IDCIFType1.setText("ID");

        jButton_ConsultCIFType.setBackground(new java.awt.Color(214, 61, 92));
        jButton_ConsultCIFType.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ConsultCIFType.setText("Consultar");
        jButton_ConsultCIFType.setToolTipText("");
        jButton_ConsultCIFType.setBorder(null);
        jButton_ConsultCIFType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ConsultCIFType.setFocusable(false);
        jButton_ConsultCIFType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultCIFTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BackgroundLayout = new javax.swing.GroupLayout(jPanel_Background);
        jPanel_Background.setLayout(jPanel_BackgroundLayout);
        jPanel_BackgroundLayout.setHorizontalGroup(
            jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                        .addComponent(jButton_ConsultCIFType, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_InsertCIFType, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_DeleteCIFType, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                        .addGroup(jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(jLabel_IDCIFType1)
                            .addComponent(jComboBox_CIFType1, 0, 201, Short.MAX_VALUE)
                            .addComponent(jSeparator14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_BackgroundLayout.setVerticalGroup(
            jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BackgroundLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_CIFType1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_IDCIFType1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_DeleteCIFType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_InsertCIFType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ConsultCIFType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel_BackgroundPrimary.setBackground(new java.awt.Color(240, 240, 240));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(119, 123, 125));
        jLabel28.setText("BUSCAR EXPEDIENTE");

        jTextField_Search.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_Search.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_Search.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_Search.setBorder(null);
        jTextField_Search.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_SearchKeyTyped(evt);
            }
        });

        jSeparator27.setBackground(new java.awt.Color(26, 97, 186));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(119, 123, 125));
        jLabel8.setText("EXPEDIENTE PERSONAL");

        jComboBox_IDPersonCIF.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_IDPersonCIF.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_IDPersonCIF.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_IDPersonCIF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_IDPersonCIFItemStateChanged(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(26, 97, 186));

        jLabel_IDPerson.setText("ID");

        javax.swing.GroupLayout jPanel_BackgroundPrimaryLayout = new javax.swing.GroupLayout(jPanel_BackgroundPrimary);
        jPanel_BackgroundPrimary.setLayout(jPanel_BackgroundPrimaryLayout);
        jPanel_BackgroundPrimaryLayout.setHorizontalGroup(
            jPanel_BackgroundPrimaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BackgroundPrimaryLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel_BackgroundPrimaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_IDPerson)
                    .addComponent(jLabel8)
                    .addGroup(jPanel_BackgroundPrimaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_IDPersonCIF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_BackgroundPrimaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_Search, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BackgroundPrimaryLayout.setVerticalGroup(
            jPanel_BackgroundPrimaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BackgroundPrimaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BackgroundPrimaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BackgroundPrimaryLayout.createSequentialGroup()
                        .addComponent(jComboBox_IDPersonCIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_IDPerson)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_BackgroundPrimary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Background, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_BackgroundPrimary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Pág 2", jPanel2);

        jLabel_Code.setText("Code");

        jButton_Save.setBackground(new java.awt.Color(214, 61, 92));
        jButton_Save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Save.setText("Guardar");
        jButton_Save.setToolTipText("");
        jButton_Save.setBorder(null);
        jButton_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Save.setFocusable(false);
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jLabel_Profile.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel_Profile.setForeground(new java.awt.Color(202, 202, 202));
        jLabel_Profile.setText("Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Code)
                        .addGap(237, 237, 237)
                        .addComponent(jLabel_Profile))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Code)
                    .addComponent(jLabel_Profile)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 740, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        // TODO add your handling code here:
        JFManageCIF viewR = new JFManageCIF();

        //Mostrar vista Principal
        viewR.setLocationRelativeTo(null);
        //Guardar datos en variables
        viewR.jLabel_Code.setText(this.jLabel_Code.getText());
        viewR.jLabel_Profile.setText(this.jLabel_Profile.getText());
        this.dispose();
        viewR.setVisible(true);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    int xy, xx;
    private void jPanel_SidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel_SidebarMouseDragged

    private void jPanel_SidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel_SidebarMousePressed

    private void jPanel_SidebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_jPanel_SidebarMouseReleased

    private void jComboBox_CIFTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_CIFTypeItemStateChanged
        // TODO add your handling code here:
        GetDataCIFType();
    }//GEN-LAST:event_jComboBox_CIFTypeItemStateChanged

    private void jButton_InsertCIFTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertCIFTypeActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        int N1 = random.nextInt(100);
        int N2 = random.nextInt(50);
        String Complement = "CIF_CIFTYPE";
        String IDCIF =  Complement + N1 + N2;
                
        LB_CIF CIFType =  (LB_CIF) this.jComboBox_CIFType1.getSelectedItem();
        String idCIFType = CIFType.getID_CIFType();
            
        //Insert CIF
        String rptaRegistro = LB.InsertCIF_CIFType(IDCIF, ID, idCIFType);

        if (rptaRegistro != null)
        {
            JOptionPane.showMessageDialog(null, "CIF_CIFType " + IDCIF + "\n" + rptaRegistro, "AA Control - CIF", JOptionPane.INFORMATION_MESSAGE);
            //listar
            //this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "CIF_CIFType " + IDCIF + "\n" + rptaRegistro, "AA Control - CIF", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_InsertCIFTypeActionPerformed

    private void jButton_DeleteCIFTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteCIFTypeActionPerformed
        // TODO add your handling code here:

        int rowDelete = this.jTable_CIF_CIFType.getSelectedRow();
        /*numero de la cantidad de filas seleccionadas
        si no se selecciona ninguna el resultado será 0*/
        int numFS = this.jTable_CIF_CIFType.getSelectedRowCount();

        if (rowDelete >=0 && numFS == 1)
        {
            String IDD = String.valueOf(this.jTable_CIF_CIFType.getValueAt(rowDelete, 0));
            LB.setID_CIF_CIFType(IDD);
            int rptaCategory = JOptionPane.showConfirmDialog(null, "Would you like to remove the following Cif_CifType ? \n" + IDD);
            //si la respuesta es si el valor de rptaUsuario será 1, no -> 2, cancelar -> 3
            if (rptaCategory == 0)
            {
                //eliminar persona segun su dni
                int rsta = LB.DeleteCif_CifType();
                if (rsta > 0)
                {
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Removed Unrealized !", "AA Control - Cif_CifType", JOptionPane.ERROR_MESSAGE);
                }
            }
            ListCIF_CIFType();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Select one row to remove ! \n\n" +
                "Once removed AA Control may not get it back", "AA Control - Cif_CifType", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_DeleteCIFTypeActionPerformed

    private void jComboBox_CIFType1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_CIFType1ItemStateChanged
        // TODO add your handling code here:
        GetDataCIFType1();
    }//GEN-LAST:event_jComboBox_CIFType1ItemStateChanged

    private void jButton_ConsultCIFTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultCIFTypeActionPerformed
        // TODO add your handling code here:
        ListCIF_CIFType();

    }//GEN-LAST:event_jButton_ConsultCIFTypeActionPerformed

    private void jTextField_SearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchKeyTyped
        // TODO add your handling code here:
        LBKE.NumbersAndCharactersMinAndCharactersMayus(evt);
    }//GEN-LAST:event_jTextField_SearchKeyTyped

    private void jComboBox_IDPersonCIFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_IDPersonCIFItemStateChanged
        // TODO add your handling code here:
        GetDataPerson();
    }//GEN-LAST:event_jComboBox_IDPersonCIFItemStateChanged

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:

        if (jDateChooser_DateOfAdmission.getCalendar() != null)
        {
            String PaymentMethod = jComboBox_PaymentMethod.getSelectedItem().toString();
            String Denomination = jComboBox_Denomination.getSelectedItem().toString();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String DateOfAdmission = dateFormat.format(jDateChooser_DateOfAdmission.getDate());

            LB_CIF CIFType =  (LB_CIF) this.jComboBox_CIFType.getSelectedItem();
            String idCIFType = CIFType.getID_CIFType();

            //String CIFType = jComboBox_CIFType.getSelectedItem().toString();
            String Classification = jComboBox_Classification.getSelectedItem().toString();
            String TypeOfCurrency = jComboBox_TypeOfCurrency.getSelectedItem().toString();

            LB_Person PERSON0 =  (LB_Person) this.jComboBox_IDPersonCIF.getSelectedItem();
            String IDPersonCIF0 = PERSON0.getID_Person();

            //String IDPersonCIF = jComboBox_IDPersonCIF.getSelectedItem().toString();
            String SearchPerson = jTextField_Search.getText();

            if (Actualizar == true)
            {
                //UPDATE

                LB = new LB_CIF(PaymentMethod, Denomination, DateOfAdmission,
                    TypeOfCurrency, null, idCIFType, null, Classification, ID,
                    null, null, null, null, null, null, null, null, null, null, null,
                    null, null, null, null, null, null, null, null, null);

                Response = LB.UpdateCIF(idCIFType);
                if (LB.eye > 0)
                {
                    JOptionPane.showMessageDialog(null, "CIF " + LB.getID_Person() + "\n" + Response, "AA Control - CIF", JOptionPane.INFORMATION_MESSAGE);
                    //listar
                    //this.dispose();
                }
                Actualizar = false;
            }
            else
            {
                //SAVE

                LB_Person PERSON =  (LB_Person) this.jComboBox_IDPersonCIF.getSelectedItem();
                String IDPersonCIF = PERSON.getID_Person();

                //String IDPersonCIF = jComboBox_IDPersonCIF.getSelectedItem().toString();

                LB = new LB_CIF(PaymentMethod, Denomination, DateOfAdmission,
                    TypeOfCurrency, null, idCIFType, null, Classification, IDPersonCIF,
                    null, null, null, null, null, null, null, null, null, null, null,
                    null, null, null, null, null, null, null, null, null);

                LB_CIF CIFTypes =  (LB_CIF) this.jComboBox_CIFType.getSelectedItem();
                String IDCIFType = CIFTypes.getID_CIFType();

                Random random = new Random();
                int N1 = random.nextInt(100);
                int N2 = random.nextInt(50);
                String Complement = "CIF_CIFTYPE";
                String IDCIF =  Complement + N1 + N2;

                //Insert CIF
                String rptaRegistro = LB.Insert(IDCIFType, IDCIF);

                if (rptaRegistro != null)
                {
                    JOptionPane.showMessageDialog(null, "CIF " + IDPersonCIF + "\n" + rptaRegistro, "AA Control - CIF", JOptionPane.INFORMATION_MESSAGE);
                    //listar
                    //this.dispose();
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "The DateOfAdmission Is Required !", "AA Control - CIF", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jTextField_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchKeyReleased
        // TODO add your handling code here:
        LB.SearchPersonEnabled(this.jComboBox_IDPersonCIF, this.jTextField_Search.getText());
    }//GEN-LAST:event_jTextField_SearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDCIF dialog = new JDCIF(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_ConsultCIFType;
    public javax.swing.JButton jButton_DeleteCIFType;
    public javax.swing.JButton jButton_InsertCIFType;
    public javax.swing.JButton jButton_Save;
    private javax.swing.JComboBox<String> jComboBox_CIFType;
    private javax.swing.JComboBox<String> jComboBox_CIFType1;
    private javax.swing.JComboBox<String> jComboBox_Classification;
    public javax.swing.JComboBox<String> jComboBox_Denomination;
    public javax.swing.JComboBox<String> jComboBox_IDPersonCIF;
    public javax.swing.JComboBox<String> jComboBox_PaymentMethod;
    public javax.swing.JComboBox<String> jComboBox_TypeOfCurrency;
    public com.toedter.calendar.JDateChooser jDateChooser_DateOfAdmission;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Close;
    public javax.swing.JLabel jLabel_Code;
    private javax.swing.JLabel jLabel_IDCIFType;
    private javax.swing.JLabel jLabel_IDCIFType1;
    public javax.swing.JLabel jLabel_IDPerson;
    public javax.swing.JLabel jLabel_Profile;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel_Background;
    public javax.swing.JPanel jPanel_BackgroundPrimary;
    private javax.swing.JPanel jPanel_Sidebar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JTable jTable_CIF_CIFType;
    public javax.swing.JTextField jTextField_Search;
    // End of variables declaration//GEN-END:variables
}
