/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layer_Presentation;

import Layer_Business.LB_BranchOffice;
import Layer_Business.LB_Career;
import Layer_Business.LB_KeyEvent;
import Layer_Business.LB_Level;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author KGR
 */
public class JDLevel extends java.awt.Dialog {

    /**
     * Creates new form JDLevel
     */
    LB_Career LBC = new LB_Career();
    LB_Level LB = new LB_Level();
    LB_KeyEvent LBKE = new LB_KeyEvent();
    public Boolean Actualizar = false;
    String Response;
    public String ID;
    LB_BranchOffice LBBO = new LB_BranchOffice();
    
    public JDLevel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        ListCarrer();
        ListBranchOffice();
    }
    
    public void ListBranchOffice()
    {
        try 
        {
            LBBO.ListBranchOfficeCBO(this.jComboBox_BranchOffice);
        }
        catch (Exception ex) 
        {
            System.out.println(ex.getMessage());
        }
        
    }
     
    public void GetDataBranchOffice()
    {
        LB_BranchOffice Office =  (LB_BranchOffice) this.jComboBox_BranchOffice.getSelectedItem();
        String idO = Office.getID_BranchOffice();
        this.jLabel_BranchOffice.setText(idO);
    }
    
    public void ListCarrer()
    {
        LBC.ListCareer(this.jComboBox_ID_Career);
    }
    
    public void GetDataCarrer()
    {
        LB_Career PERDirect =  (LB_Career) this.jComboBox_ID_Career.getSelectedItem();
        String id = PERDirect.getID_Career();
        this.jLabel_IDCareer.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jComboBox_State = new javax.swing.JComboBox<>();
        jTextField_Description = new javax.swing.JTextField();
        jTextField_IDLevel = new javax.swing.JTextField();
        jComboBox_ID_Career = new javax.swing.JComboBox<>();
        jPanel_OpeningDate = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jDateChooser_OpeningDate = new com.toedter.calendar.JDateChooser();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextField_AcademicGrade = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel_IDCareer = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Enphatic = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSpinner_MinimunNote = new javax.swing.JSpinner();
        jSpinner_Credits = new javax.swing.JSpinner();
        jCheckBox_NoEnphatic = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jComboBox_BranchOffice = new javax.swing.JComboBox<>();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel_BranchOffice = new javax.swing.JLabel();
        jButton_Save = new javax.swing.JButton();
        jLabel_Code = new javax.swing.JLabel();
        jLabel_Profile = new javax.swing.JLabel();
        jPanel_Sidebar = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPane3.setBackground(new java.awt.Color(240, 240, 240));
        jTabbedPane3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(119, 123, 125));
        jLabel6.setText("ID");

        jSeparator5.setBackground(new java.awt.Color(26, 97, 186));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(119, 123, 125));
        jLabel7.setText("DESCRIPCIÓN");

        jSeparator6.setBackground(new java.awt.Color(26, 97, 186));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(119, 123, 125));
        jLabel14.setText("CARRERA");

        jSeparator13.setBackground(new java.awt.Color(26, 97, 186));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(119, 123, 125));
        jLabel20.setText("ESTADO");

        jSeparator19.setBackground(new java.awt.Color(26, 97, 186));

        jComboBox_State.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_State.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_State.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_State.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Inhabilitado" }));

        jTextField_Description.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_Description.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_Description.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_Description.setBorder(null);
        jTextField_Description.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_Description.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_DescriptionKeyTyped(evt);
            }
        });

        jTextField_IDLevel.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_IDLevel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_IDLevel.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_IDLevel.setBorder(null);
        jTextField_IDLevel.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_IDLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDLevelKeyTyped(evt);
            }
        });

        jComboBox_ID_Career.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_ID_Career.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_ID_Career.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_ID_Career.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ID_CareerItemStateChanged(evt);
            }
        });

        jPanel_OpeningDate.setBackground(new java.awt.Color(240, 240, 240));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(119, 123, 125));
        jLabel24.setText("APERTURA");

        jDateChooser_OpeningDate.setBackground(new java.awt.Color(240, 240, 240));
        jDateChooser_OpeningDate.setForeground(new java.awt.Color(105, 105, 105));
        jDateChooser_OpeningDate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jSeparator23.setBackground(new java.awt.Color(26, 97, 186));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(119, 123, 125));
        jLabel8.setText("GRADO ACADÉMICO");

        jTextField_AcademicGrade.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_AcademicGrade.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_AcademicGrade.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_AcademicGrade.setBorder(null);
        jTextField_AcademicGrade.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_AcademicGrade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_AcademicGradeKeyTyped(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(26, 97, 186));

        javax.swing.GroupLayout jPanel_OpeningDateLayout = new javax.swing.GroupLayout(jPanel_OpeningDate);
        jPanel_OpeningDate.setLayout(jPanel_OpeningDateLayout);
        jPanel_OpeningDateLayout.setHorizontalGroup(
            jPanel_OpeningDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_OpeningDateLayout.createSequentialGroup()
                .addGroup(jPanel_OpeningDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_OpeningDateLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel_OpeningDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator23)
                            .addComponent(jLabel24)
                            .addComponent(jDateChooser_OpeningDate, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                    .addGroup(jPanel_OpeningDateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_OpeningDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_AcademicGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel_OpeningDateLayout.setVerticalGroup(
            jPanel_OpeningDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_OpeningDateLayout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(24, 24, 24)
                .addComponent(jDateChooser_OpeningDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_AcademicGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_IDCareer.setForeground(new java.awt.Color(105, 105, 105));
        jLabel_IDCareer.setText("ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_IDCareer)
                        .addContainerGap(585, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_ID_Career, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel14)
                            .addComponent(jSeparator13)
                            .addComponent(jSeparator19)
                            .addComponent(jComboBox_State, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_IDLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator6)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addComponent(jPanel_OpeningDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_IDLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(19, 19, 19)
                        .addComponent(jComboBox_State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_ID_Career, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_OpeningDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_IDCareer)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Pág 1", jPanel3);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(119, 123, 125));
        jLabel9.setText("ÉNFASIS");

        jTextField_Enphatic.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_Enphatic.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_Enphatic.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_Enphatic.setToolTipText("");
        jTextField_Enphatic.setBorder(null);
        jTextField_Enphatic.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_Enphatic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_EnphaticKeyTyped(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(26, 97, 186));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(119, 123, 125));
        jLabel10.setText("CRÉDITOS");

        jSeparator9.setBackground(new java.awt.Color(26, 97, 186));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(119, 123, 125));
        jLabel11.setText("NOTA MÍNIMA");

        jSeparator10.setBackground(new java.awt.Color(26, 97, 186));

        jSpinner_MinimunNote.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jSpinner_Credits.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jCheckBox_NoEnphatic.setBackground(new java.awt.Color(240, 240, 240));
        jCheckBox_NoEnphatic.setForeground(new java.awt.Color(105, 105, 105));
        jCheckBox_NoEnphatic.setText("No tiene Énfasis.");
        jCheckBox_NoEnphatic.setToolTipText("No have enphatic.");
        jCheckBox_NoEnphatic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_NoEnphaticMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinner_MinimunNote, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_Enphatic, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                        .addComponent(jSpinner_Credits, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_NoEnphatic)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Enphatic, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_NoEnphatic))
                .addGap(13, 13, 13)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner_Credits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSpinner_MinimunNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Pág 2", jPanel2);

        jPanel4.setBackground(new java.awt.Color(240, 240, 240));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(119, 123, 125));
        jLabel32.setText("SEDE/SUCURSAL");

        jComboBox_BranchOffice.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_BranchOffice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_BranchOffice.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_BranchOffice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_BranchOfficeItemStateChanged(evt);
            }
        });

        jSeparator18.setBackground(new java.awt.Color(38, 45, 53));

        jLabel_BranchOffice.setText("ID");

        jButton_Save.setBackground(new java.awt.Color(214, 61, 92));
        jButton_Save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Save.setText("Guardar");
        jButton_Save.setToolTipText("");
        jButton_Save.setBorder(null);
        jButton_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Save.setFocusable(false);
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel32)
                        .addComponent(jLabel_BranchOffice)
                        .addComponent(jSeparator18)
                        .addComponent(jComboBox_BranchOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_BranchOffice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(31, 31, 31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel_BranchOffice)
                .addGap(116, 116, 116)
                .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Pág 3", jPanel4);

        jLabel_Code.setText("Code");

        jLabel_Profile.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel_Profile.setForeground(new java.awt.Color(202, 202, 202));
        jLabel_Profile.setText("Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Code)
                        .addGap(226, 226, 226)
                        .addComponent(jLabel_Profile))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane3)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Code)
                    .addComponent(jLabel_Profile)))
        );

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel_Sidebar.setBackground(new java.awt.Color(29, 34, 39));
        jPanel_Sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseDragged(evt);
            }
        });
        jPanel_Sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseReleased(evt);
            }
        });

        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/left_15px.png"))); // NOI18N
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NIVEL");

        javax.swing.GroupLayout jPanel_SidebarLayout = new javax.swing.GroupLayout(jPanel_Sidebar);
        jPanel_Sidebar.setLayout(jPanel_SidebarLayout);
        jPanel_SidebarLayout.setHorizontalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel_SidebarLayout.setVerticalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        add(jPanel_Sidebar, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jTextField_DescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DescriptionKeyTyped
        // TODO add your handling code here:
        LBKE.NumbersAndCharactersMinAndCharactersMayus(evt);
    }//GEN-LAST:event_jTextField_DescriptionKeyTyped

    private void jTextField_IDLevelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDLevelKeyTyped
        // TODO add your handling code here:
        LBKE.NumbersAndCharactersMayus(evt);
    }//GEN-LAST:event_jTextField_IDLevelKeyTyped

    private void jComboBox_ID_CareerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ID_CareerItemStateChanged
        // TODO add your handling code here:
        GetDataCarrer();
    }//GEN-LAST:event_jComboBox_ID_CareerItemStateChanged

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:

        if (!"".equals(jTextField_IDLevel.getText()))
        {
            if (jComboBox_ID_Career.getSelectedItem()!= null)
            {
                if (!"".equals(jTextField_Description.getText()))
                {
                    if (jDateChooser_OpeningDate.getCalendar() != null)
                    {
                        if (!"".equals(jTextField_AcademicGrade.getText()))
                        {
                            if (!"".equals(jTextField_Enphatic.getText()))
                            {
                                String IDLevel = jTextField_IDLevel.getText();
                                String Complement = "LEV_"+IDLevel;
                                String State = jComboBox_State.getSelectedItem().toString();
                                String Description = jTextField_Description.getText();

                                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                                String OpeningDate = dateFormat.format(jDateChooser_OpeningDate.getDate());

                                String AcademicGrade = jTextField_AcademicGrade.getText();
                                String Enphatic = jTextField_Enphatic.getText();
                                int Credits = Integer.parseInt(this.jSpinner_Credits.getValue().toString());

                                int MinimumNote = Integer.parseInt(this.jSpinner_MinimunNote.getValue().toString());
                                //String CIFType = jComboBox_CIFType.getSelectedItem().toString();
                                LB_Career PERDirect =  (LB_Career) this.jComboBox_ID_Career.getSelectedItem();
                                String IDCAR = PERDirect.getID_Career();
                                
                                LB_BranchOffice Office =  (LB_BranchOffice) this.jComboBox_BranchOffice.getSelectedItem();
                                String idO = Office.getID_BranchOffice();

                                if (Actualizar == true)
                                {
                                    //UPDATE

                                    LB = new LB_Level(ID, IDCAR,
                                        OpeningDate, AcademicGrade, Description, Enphatic, Credits,
                                            idO, MinimumNote, State);

                                    Response = LB.Update();
                                    if (LB.eye > 0)
                                    {
                                        JOptionPane.showMessageDialog(null, "Level " + LB.getID_Level()+ "\n" + Response, "AA Control - Level", JOptionPane.INFORMATION_MESSAGE);
                                        //listar
                                        //this.dispose();
                                    }
                                    Actualizar = false;
                                }
                                else
                                {
                                    //SAVE

                                    LB = new LB_Level(Complement, IDCAR,
                                        OpeningDate, AcademicGrade, Description, Enphatic, Credits,
                                            idO, MinimumNote, State);

                                    //Insert CIF
                                    String rptaRegistro = LB.Insert();

                                    if (rptaRegistro != null)
                                    {
                                        JOptionPane.showMessageDialog(null, "Level " + IDLevel + "\n" + rptaRegistro, "AA Control - Level", JOptionPane.INFORMATION_MESSAGE);
                                        //listar
                                        //this.dispose();
                                    }
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null, "The Enphatic Is Required !", "AA Control - Level", JOptionPane.WARNING_MESSAGE);
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "The AcademicGrade Is Required !", "AA Control - Level", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "The OpeningDate Is Required !", "AA Control - Level", JOptionPane.WARNING_MESSAGE);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "The Description Is Required !", "AA Control - Level", JOptionPane.WARNING_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "The ID_Career Is Required !", "AA Control - Level", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "The ID Is Required !", "AA Control - Level", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        // TODO add your handling code here:
        JFManageLevel viewR = new JFManageLevel();

        //Mostrar vista Principal
        viewR.setLocationRelativeTo(null);
        //Guardar datos en variables
        viewR.jLabel_Code.setText(this.jLabel_Code.getText());
        viewR.jLabel_Profile.setText(this.jLabel_Profile.getText());
        this.dispose();
        viewR.setVisible(true);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    int xy, xx;
    private void jPanel_SidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel_SidebarMouseDragged

    private void jPanel_SidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel_SidebarMousePressed

    private void jPanel_SidebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_jPanel_SidebarMouseReleased

    private void jTextField_AcademicGradeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AcademicGradeKeyTyped
        // TODO add your handling code here:
        LBKE.CharactersMayusAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_AcademicGradeKeyTyped

    private void jTextField_EnphaticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EnphaticKeyTyped
        // TODO add your handling code here:
        LBKE.CharactersMayusAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_EnphaticKeyTyped

    private void jCheckBox_NoEnphaticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_NoEnphaticMouseClicked
        // TODO add your handling code here:
        if (jCheckBox_NoEnphatic.isSelected()) 
        {
            jTextField_Enphatic.setEditable(false);
            jTextField_Enphatic.setText("null");
        }
        else
        {
            jTextField_Enphatic.setEditable(true);
            jTextField_Enphatic.setText("");
        }
    }//GEN-LAST:event_jCheckBox_NoEnphaticMouseClicked

    private void jComboBox_BranchOfficeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_BranchOfficeItemStateChanged
        // TODO add your handling code here:
        GetDataBranchOffice();
    }//GEN-LAST:event_jComboBox_BranchOfficeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDLevel dialog = new JDLevel(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Save;
    private javax.swing.JCheckBox jCheckBox_NoEnphatic;
    private javax.swing.JComboBox<String> jComboBox_BranchOffice;
    private javax.swing.JComboBox<String> jComboBox_ID_Career;
    private javax.swing.JComboBox<String> jComboBox_State;
    public com.toedter.calendar.JDateChooser jDateChooser_OpeningDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_BranchOffice;
    private javax.swing.JLabel jLabel_Close;
    public javax.swing.JLabel jLabel_Code;
    private javax.swing.JLabel jLabel_IDCareer;
    public javax.swing.JLabel jLabel_Profile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel_OpeningDate;
    private javax.swing.JPanel jPanel_Sidebar;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JSpinner jSpinner_Credits;
    public javax.swing.JSpinner jSpinner_MinimunNote;
    private javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JTextField jTextField_AcademicGrade;
    public javax.swing.JTextField jTextField_Description;
    public javax.swing.JTextField jTextField_Enphatic;
    public javax.swing.JTextField jTextField_IDLevel;
    // End of variables declaration//GEN-END:variables
}
