/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layer_Presentation;

import Layer_Business.LB_KeyEvent;
import Layer_Business.LB_Level;
import Layer_Business.LB_Subject;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author KGR
 */
public class JDOfferAcademic extends javax.swing.JDialog {

    /**
     * Creates new form JDSubject
     */
    LB_KeyEvent LBKE = new LB_KeyEvent();
    public Boolean Actualizar = false;
    String Response;
    public String ID;
    LB_Subject LB = new LB_Subject();
    LB_Level LBL = new LB_Level();
    private int ApplyScholarshipDiscounts = 0;
    private int DegreeTest = 0;
    private int ProfessionalPractice = 0;
    private int AppliesUVirtualRetirement = 0;
    
    public JDOfferAcademic(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        ListLevel();
    }
    
    public void ListLevel()
    {
//        LBL.ListLevel(this.jComboBox_ID_Level);
    }
    
    public void GetDataLevel()
    {
//        LB_Level ObjLlevel =  (LB_Level) this.jComboBox_ID_Level.getSelectedItem();
//        String id = ObjLlevel.getID_Level();
//        this.jLabel_IDLevel.setText(id);
//        
//        if (this.jComboBox_ID_Level.getItemCount() > 0) 
//        {
//            int TotalLevelCredits = LBL.GetLevelCredits(id);
//            int TotalSubjectCredits = LB.GetSubajectCredits(id);
//            jLabel_TotalLavelCredits.setText(String.valueOf(TotalLevelCredits));
//            jLabel_TotalSubjectCredits.setText(String.valueOf(TotalSubjectCredits));
//            
//            CalcCredits();
//        }
        
    }
    
    private void CalcCredits()
    {
//        try 
//        {
//            int Credts = Integer.parseInt(this.jSpinner_Credits.getValue().toString());
//            int TotlLevelCredts = Integer.valueOf(jLabel_TotalLavelCredits.getText());
//            int TotlSubjectCredts = Integer.valueOf(jLabel_TotalSubjectCredits.getText());
//
//            int result = (Credts + TotlSubjectCredts);
//            if (result > TotlLevelCredts) 
//            {
//                jButton_Save.setEnabled(false);
//                JOptionPane.showMessageDialog(null, "The Credits of this Subject exceeds the Level Credits " + "(" + result + ")" , "AA Control - Subject", JOptionPane.WARNING_MESSAGE);
//            }
//            else
//            {
//                jButton_Save.setEnabled(true);
//            }
//        } catch (Exception e) 
//        {
//            System.out.println(e.getMessage());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Sidebar = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Code = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_IDAcademicOffering = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jComboBox_IDBranchOffice = new javax.swing.JComboBox<>();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jComboBox_Period = new javax.swing.JComboBox<>();
        jSeparator11 = new javax.swing.JSeparator();
        jDateChooser_Year = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel_IDLevel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox_IDClassRoom = new javax.swing.JComboBox<>();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel_IDLevel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox_SecondFD1 = new javax.swing.JComboBox<>();
        jComboBox_MinuteFD1 = new javax.swing.JComboBox<>();
        jComboBox_HourFD1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jComboBox_DayWeek = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_HourSD = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_MinuteSD = new javax.swing.JComboBox<>();
        jComboBox_SecondSD = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jComboBox_Period5 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jTextField_IDSubject2 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jTextField_IDSubject3 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jTextField_IDSubject1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField_IDSubject4 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jComboBox_Period6 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_ID_Level1 = new javax.swing.JComboBox<>();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel_IDLevel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_ID_Level2 = new javax.swing.JComboBox<>();
        jSeparator28 = new javax.swing.JSeparator();
        jLabel_IDLevel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox_ID_Level3 = new javax.swing.JComboBox<>();
        jSeparator29 = new javax.swing.JSeparator();
        jLabel_IDLevel6 = new javax.swing.JLabel();
        jButton_Save = new javax.swing.JButton();
        jLabel_Profile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Sidebar.setBackground(new java.awt.Color(29, 34, 39));
        jPanel_Sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseDragged(evt);
            }
        });
        jPanel_Sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseReleased(evt);
            }
        });

        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/left_15px.png"))); // NOI18N
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OFERTA ACADÉMICA");

        javax.swing.GroupLayout jPanel_SidebarLayout = new javax.swing.GroupLayout(jPanel_Sidebar);
        jPanel_Sidebar.setLayout(jPanel_SidebarLayout);
        jPanel_SidebarLayout.setHorizontalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addGap(258, 258, 258)
                .addComponent(jLabel1)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel_SidebarLayout.setVerticalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SidebarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_Code.setText("Code");

        jTabbedPane3.setBackground(new java.awt.Color(240, 240, 240));
        jTabbedPane3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(119, 123, 125));
        jLabel6.setText("ID");

        jTextField_IDAcademicOffering.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_IDAcademicOffering.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_IDAcademicOffering.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_IDAcademicOffering.setBorder(null);
        jTextField_IDAcademicOffering.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_IDAcademicOffering.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDAcademicOfferingKeyTyped(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(26, 97, 186));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(119, 123, 125));
        jLabel20.setText("SEDE");

        jComboBox_IDBranchOffice.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_IDBranchOffice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_IDBranchOffice.setForeground(new java.awt.Color(105, 105, 105));

        jSeparator19.setBackground(new java.awt.Color(26, 97, 186));

        jSeparator10.setBackground(new java.awt.Color(26, 97, 186));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(119, 123, 125));
        jLabel12.setText("PERÍODO");

        jComboBox_Period.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_Period.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_Period.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_Period.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jSeparator11.setBackground(new java.awt.Color(26, 97, 186));

        jDateChooser_Year.setBackground(new java.awt.Color(240, 240, 240));
        jDateChooser_Year.setForeground(new java.awt.Color(105, 105, 105));
        jDateChooser_Year.setDateFormatString("y");
        jDateChooser_Year.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(119, 123, 125));
        jLabel14.setText("AÑO");

        jLabel_IDLevel1.setForeground(new java.awt.Color(105, 105, 105));
        jLabel_IDLevel1.setText("ID");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(119, 123, 125));
        jLabel21.setText("AULA");

        jComboBox_IDClassRoom.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_IDClassRoom.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_IDClassRoom.setForeground(new java.awt.Color(105, 105, 105));

        jSeparator20.setBackground(new java.awt.Color(26, 97, 186));

        jLabel_IDLevel2.setForeground(new java.awt.Color(105, 105, 105));
        jLabel_IDLevel2.setText("ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_IDLevel2)
                    .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox_IDClassRoom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_IDAcademicOffering, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_IDLevel1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator10)
                                    .addComponent(jDateChooser_Year, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox_Period, 0, 164, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                        .addComponent(jComboBox_IDBranchOffice, 0, 540, Short.MAX_VALUE)
                        .addComponent(jSeparator19)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_IDAcademicOffering, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooser_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, 0)
                        .addComponent(jComboBox_Period, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_IDBranchOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_IDLevel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox_IDClassRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_IDLevel2)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Pág 1", jPanel3);

        jPanel4.setBackground(new java.awt.Color(240, 240, 240));

        jLabel11.setText("Hour");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(119, 123, 125));
        jLabel3.setText("DÍA DE SEMANA");

        jLabel15.setText("Minute");

        jLabel16.setText("Second");

        jComboBox_SecondFD1.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_SecondFD1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_SecondFD1.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_SecondFD1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jComboBox_MinuteFD1.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_MinuteFD1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_MinuteFD1.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_MinuteFD1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jComboBox_HourFD1.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_HourFD1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_HourFD1.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_HourFD1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(119, 123, 125));
        jLabel17.setText("HORA INICIO");

        jComboBox_DayWeek.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_DayWeek.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_DayWeek.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_DayWeek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sábado" }));

        jLabel8.setText("Hour");

        jComboBox_HourSD.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_HourSD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_HourSD.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_HourSD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        jLabel10.setText("Minute");

        jComboBox_MinuteSD.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_MinuteSD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_MinuteSD.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_MinuteSD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jComboBox_SecondSD.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_SecondSD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_SecondSD.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_SecondSD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel18.setText("Second");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(119, 123, 125));
        jLabel19.setText("HORA FINAL");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setText("Available");

        jSeparator6.setBackground(new java.awt.Color(26, 97, 186));

        jComboBox_Period5.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_Period5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_Period5.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_Period5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Tutoria", "Suficiencia" }));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(119, 123, 125));
        jLabel23.setText("TIPO DE OFERTA");

        jSeparator7.setBackground(new java.awt.Color(26, 97, 186));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(119, 123, 125));
        jLabel24.setText("HORARIO");

        jCheckBox1.setBackground(new java.awt.Color(240, 240, 240));
        jCheckBox1.setForeground(new java.awt.Color(105, 105, 105));
        jCheckBox1.setText("Horario Virtual");

        jSeparator8.setBackground(new java.awt.Color(26, 97, 186));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(119, 123, 125));
        jLabel25.setText("GRUPO Y CUPO");

        jTextField_IDSubject2.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_IDSubject2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_IDSubject2.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_IDSubject2.setBorder(null);
        jTextField_IDSubject2.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_IDSubject2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDSubject2KeyTyped(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(26, 97, 186));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(119, 123, 125));
        jLabel26.setText("MATRICULADOS");

        jTextField_IDSubject3.setEditable(false);
        jTextField_IDSubject3.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_IDSubject3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_IDSubject3.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_IDSubject3.setText("1");
        jTextField_IDSubject3.setBorder(null);
        jTextField_IDSubject3.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_IDSubject3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDSubject3KeyTyped(evt);
            }
        });

        jSeparator12.setBackground(new java.awt.Color(26, 97, 186));

        jTextField_IDSubject1.setEditable(false);
        jTextField_IDSubject1.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_IDSubject1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_IDSubject1.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_IDSubject1.setBorder(null);
        jTextField_IDSubject1.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_IDSubject1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDSubject1KeyTyped(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(119, 123, 125));
        jLabel27.setText("DISPONIBLE");

        jTextField_IDSubject4.setEditable(false);
        jTextField_IDSubject4.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_IDSubject4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_IDSubject4.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_IDSubject4.setBorder(null);
        jTextField_IDSubject4.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_IDSubject4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDSubject4KeyTyped(evt);
            }
        });

        jSeparator13.setBackground(new java.awt.Color(26, 97, 186));

        jComboBox_Period6.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_Period6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_Period6.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_Period6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensual", "Bimensual", "Trimestral", "Cuatrimestral", "Quintomestral", "Semestral", "Anual" }));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(119, 123, 125));
        jLabel29.setText("MODO DE OFERTA");

        jSeparator14.setBackground(new java.awt.Color(26, 97, 186));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_IDSubject1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator12))
                                        .addGap(45, 45, 45))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator14, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(jLabel27)
                                    .addComponent(jTextField_IDSubject4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator13)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jComboBox_Period6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jSeparator7)
                                        .addGap(40, 40, 40)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jCheckBox1)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(60, 60, 60)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel25)
                                                .addGap(15, 15, 15))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jTextField_IDSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_IDSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21)))))))
                        .addGap(65, 65, 65))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jComboBox_DayWeek, 0, 133, Short.MAX_VALUE)
                                .addGap(17, 17, 17))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_HourFD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jComboBox_MinuteFD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_SecondFD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_HourSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jComboBox_MinuteSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jComboBox_SecondSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jComboBox_Period5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jComboBox_DayWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel3))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox_HourFD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jComboBox_MinuteFD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox_SecondFD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox_HourSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jComboBox_MinuteSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox_SecondSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel22)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Period5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jTextField_IDSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_IDSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_IDSubject4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Period6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator13)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_IDSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Pág 2", jPanel4);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(119, 123, 125));
        jLabel9.setText("NIVEL");

        jComboBox_ID_Level1.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_ID_Level1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_ID_Level1.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_ID_Level1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ID_Level1ItemStateChanged(evt);
            }
        });

        jSeparator27.setBackground(new java.awt.Color(26, 97, 186));

        jLabel_IDLevel4.setForeground(new java.awt.Color(105, 105, 105));
        jLabel_IDLevel4.setText("ID");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(119, 123, 125));
        jLabel13.setText("PROFESOR");

        jComboBox_ID_Level2.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_ID_Level2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_ID_Level2.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_ID_Level2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ID_Level2ItemStateChanged(evt);
            }
        });

        jSeparator28.setBackground(new java.awt.Color(26, 97, 186));

        jLabel_IDLevel5.setForeground(new java.awt.Color(105, 105, 105));
        jLabel_IDLevel5.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(609, 609, 609))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator27, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_ID_Level1, javax.swing.GroupLayout.Alignment.LEADING, 0, 615, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_IDLevel5)
                            .addComponent(jLabel13)
                            .addComponent(jLabel_IDLevel4)
                            .addComponent(jComboBox_ID_Level2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_ID_Level2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_IDLevel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_ID_Level1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_IDLevel4)
                .addGap(16, 16, 16))
        );

        jTabbedPane3.addTab("Pág 3", jPanel2);

        jPanel5.setBackground(new java.awt.Color(240, 240, 240));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(119, 123, 125));
        jLabel30.setText("PROFESOR");

        jComboBox_ID_Level3.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_ID_Level3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_ID_Level3.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_ID_Level3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ID_Level3ItemStateChanged(evt);
            }
        });

        jSeparator29.setBackground(new java.awt.Color(26, 97, 186));

        jLabel_IDLevel6.setForeground(new java.awt.Color(105, 105, 105));
        jLabel_IDLevel6.setText("ID");

        jButton_Save.setBackground(new java.awt.Color(214, 61, 92));
        jButton_Save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Save.setText("Guardar");
        jButton_Save.setToolTipText("");
        jButton_Save.setBorder(null);
        jButton_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Save.setFocusable(false);
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_IDLevel6)
                            .addComponent(jLabel30)
                            .addComponent(jComboBox_ID_Level3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_ID_Level3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_IDLevel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTabbedPane3.addTab("Pág 4", jPanel5);

        jLabel_Profile.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel_Profile.setForeground(new java.awt.Color(202, 202, 202));
        jLabel_Profile.setText("Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Code)
                        .addGap(219, 219, 219)
                        .addComponent(jLabel_Profile)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTabbedPane3)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Code)
                    .addComponent(jLabel_Profile))
                .addGap(81, 81, 81))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 710, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        // TODO add your handling code here:
        JFManageSubject viewR = new JFManageSubject();

        //Mostrar vista Principal
        viewR.setLocationRelativeTo(null);
        //Guardar datos en variables
        viewR.jLabel_Code.setText(this.jLabel_Code.getText());
        viewR.jLabel_Profile.setText(this.jLabel_Profile.getText());
        this.dispose();
        viewR.setVisible(true);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    int xy, xx;
    private void jPanel_SidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel_SidebarMouseDragged

    private void jPanel_SidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel_SidebarMousePressed

    private void jPanel_SidebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_jPanel_SidebarMouseReleased

    private void jComboBox_ID_Level1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ID_Level1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ID_Level1ItemStateChanged

    private void jTextField_IDSubject4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDSubject4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDSubject4KeyTyped

    private void jTextField_IDSubject1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDSubject1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDSubject1KeyTyped

    private void jTextField_IDSubject3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDSubject3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDSubject3KeyTyped

    private void jTextField_IDSubject2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDSubject2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDSubject2KeyTyped

    private void jTextField_IDAcademicOfferingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDAcademicOfferingKeyTyped
        // TODO add your handling code here:
        LBKE.NumbersAndCharactersMayus(evt);
    }//GEN-LAST:event_jTextField_IDAcademicOfferingKeyTyped

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:

//        if (!"".equals(jTextField_IDAcademicOffering.getText()))
//        {
//            if (!"".equals(jTextField_Description.getText()))
//            {
//                if (jDateChooser_OpeningDate.getCalendar() != null)
//                {
//                    String IDSubject = jTextField_IDAcademicOffering.getText();
//                    String Complement = "SUBJ_"+IDSubject;
//                    String Status = jComboBox_IDBranchOffice.getSelectedItem().toString();
//                    String Description = jTextField_Description.getText();
//
//                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//                    String OpeningDate = dateFormat.format(jDateChooser_OpeningDate.getDate());
//
//                    int Credits = Integer.parseInt(this.jSpinner_Credits.getValue().toString());
//                    int MinimunNote = Integer.parseInt(this.jSpinner_MinimunNote.getValue().toString());
//                    String Period = jComboBox_Period.getSelectedItem().toString();
//                    int HoursDuration = Integer.parseInt(this.jSpinner_HoursDuration.getValue().toString());
//                    int ExtraordinayMinimunNote = Integer.parseInt(this.jSpinner_ExtraordinayMinimunNote.getValue().toString());
//                    int MinimunQuote = Integer.parseInt(this.jSpinner_MinimunQuote.getValue().toString());
//                    String TypeOfCurrency = jComboBox_TypeOfCurrency.getSelectedItem().toString();
//                    int ReprobingAbsence = Integer.parseInt(this.jSpinner_ReprobingAbsence.getValue().toString());
//
//                    //String CIFType = jComboBox_CIFType.getSelectedItem().toString();
//                    LB_Level ObjLlevel =  (LB_Level) this.jComboBox_ID_Level.getSelectedItem();
//                    String IDLevel = ObjLlevel.getID_Level();
//
//                    if (Actualizar == true)
//                    {
//                        //UPDATE
//
//                        LB = new LB_Subject(ID, IDLevel, OpeningDate, Status, Description,
//                            Credits, MinimunNote, MinimunQuote, TypeOfCurrency,
//                            Period, ReprobingAbsence, HoursDuration, ExtraordinayMinimunNote,
//                            ApplyScholarshipDiscounts, DegreeTest, ProfessionalPractice,
//                            AppliesUVirtualRetirement);
//
//                        Response = LB.Update();
//                        if (LB.eye > 0)
//                        {
//                            JOptionPane.showMessageDialog(null, "Subject " + LB.getID_Subject()+ "\n" + Response, "AA Control - Subject", JOptionPane.INFORMATION_MESSAGE);
//                            //listar
//                            //this.dispose();
//                        }
//                        Actualizar = false;
//                    }
//                    else
//                    {
//                        //SAVE
//
//                        LB = new LB_Subject(Complement, IDLevel, OpeningDate, Status, Description,
//                            Credits, MinimunNote, MinimunQuote, TypeOfCurrency,
//                            Period, ReprobingAbsence, HoursDuration, ExtraordinayMinimunNote,
//                            ApplyScholarshipDiscounts, DegreeTest, ProfessionalPractice,
//                            AppliesUVirtualRetirement);
//
//                        //Insert CIF
//                        String rptaRegistro = LB.Insert();
//
//                        if (rptaRegistro != null)
//                        {
//                            JOptionPane.showMessageDialog(null, "Subject " + IDSubject + "\n" + rptaRegistro, "AA Control - Subject", JOptionPane.INFORMATION_MESSAGE);
//                            //listar
//                            //this.dispose();
//                        }
//                    }
//                }
//                else
//                {
//                    JOptionPane.showMessageDialog(null, "The OpeningDate Is Required !", "AA Control - Subject", JOptionPane.WARNING_MESSAGE);
//                }
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(null, "The Description Is Required !", "AA Control - Subject", JOptionPane.WARNING_MESSAGE);
//            }
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(null, "The ID Is Required !", "AA Control - Subject", JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jComboBox_ID_Level2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ID_Level2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ID_Level2ItemStateChanged

    private void jComboBox_ID_Level3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ID_Level3ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ID_Level3ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDOfferAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDOfferAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDOfferAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDOfferAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDOfferAcademic dialog = new JDOfferAcademic(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Save;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox_DayWeek;
    private javax.swing.JComboBox<String> jComboBox_HourFD1;
    private javax.swing.JComboBox<String> jComboBox_HourSD;
    private javax.swing.JComboBox<String> jComboBox_IDBranchOffice;
    private javax.swing.JComboBox<String> jComboBox_IDClassRoom;
    private javax.swing.JComboBox<String> jComboBox_ID_Level1;
    private javax.swing.JComboBox<String> jComboBox_ID_Level2;
    private javax.swing.JComboBox<String> jComboBox_ID_Level3;
    private javax.swing.JComboBox<String> jComboBox_MinuteFD1;
    private javax.swing.JComboBox<String> jComboBox_MinuteSD;
    private javax.swing.JComboBox<String> jComboBox_Period;
    private javax.swing.JComboBox<String> jComboBox_Period5;
    private javax.swing.JComboBox<String> jComboBox_Period6;
    private javax.swing.JComboBox<String> jComboBox_SecondFD1;
    private javax.swing.JComboBox<String> jComboBox_SecondSD;
    private com.toedter.calendar.JDateChooser jDateChooser_Year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_Code;
    private javax.swing.JLabel jLabel_IDLevel1;
    private javax.swing.JLabel jLabel_IDLevel2;
    private javax.swing.JLabel jLabel_IDLevel4;
    private javax.swing.JLabel jLabel_IDLevel5;
    private javax.swing.JLabel jLabel_IDLevel6;
    private javax.swing.JLabel jLabel_Profile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_Sidebar;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField_IDAcademicOffering;
    private javax.swing.JTextField jTextField_IDSubject1;
    private javax.swing.JTextField jTextField_IDSubject2;
    private javax.swing.JTextField jTextField_IDSubject3;
    private javax.swing.JTextField jTextField_IDSubject4;
    // End of variables declaration//GEN-END:variables
}
