/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layer_Presentation;

import Layer_Business.LB_KeyEvent;
import Layer_Business.LB_Level;
import Layer_Business.LB_Subject;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author KGR
 */
public class JDSubject extends javax.swing.JDialog {

    /**
     * Creates new form JDSubject
     */
    LB_KeyEvent LBKE = new LB_KeyEvent();
    public Boolean Actualizar = false;
    String Response;
    public String ID;
    LB_Subject LB = new LB_Subject();
    LB_Level LBL = new LB_Level();
    private int ApplyScholarshipDiscounts = 0;
    private int DegreeTest = 0;
    private int ProfessionalPractice = 0;
    private int AppliesUVirtualRetirement = 0;
    
    public JDSubject(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        ListLevel();
    }
    
    public void ListLevel()
    {
        LBL.ListLevel(this.jComboBox_ID_Level);
    }
    
    public void GetDataLevel()
    {
        LB_Level ObjLlevel =  (LB_Level) this.jComboBox_ID_Level.getSelectedItem();
        String id = ObjLlevel.getID_Level();
        this.jLabel_IDLevel.setText(id);
        
        if (this.jComboBox_ID_Level.getItemCount() > 0) 
        {
            int TotalLevelCredits = LBL.GetLevelCredits(id);
            int TotalSubjectCredits = LB.GetSubajectCredits(id);
            jLabel_TotalLavelCredits.setText(String.valueOf(TotalLevelCredits));
            jLabel_TotalSubjectCredits.setText(String.valueOf(TotalSubjectCredits));
            
            CalcCredits();
        }
        
    }
    
    private void CalcCredits()
    {
        try 
        {
            int Credts = Integer.parseInt(this.jSpinner_Credits.getValue().toString());
            int TotlLevelCredts = Integer.valueOf(jLabel_TotalLavelCredits.getText());
            int TotlSubjectCredts = Integer.valueOf(jLabel_TotalSubjectCredits.getText());

            int result = (Credts + TotlSubjectCredts);
            if (result > TotlLevelCredts) 
            {
                jButton_Save.setEnabled(false);
                JOptionPane.showMessageDialog(null, "The Credits of this Subject exceeds the Level Credits " + "(" + result + ")" , "AA Control - Subject", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                jButton_Save.setEnabled(true);
            }
        } catch (Exception e) 
        {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Sidebar = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Code = new javax.swing.JLabel();
        jButton_Save = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_IDSubject = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jComboBox_Status = new javax.swing.JComboBox<>();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSpinner_ExtraordinayMinimunNote = new javax.swing.JSpinner();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSpinner_MinimunNote = new javax.swing.JSpinner();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jDateChooser_OpeningDate = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Description = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jComboBox_Period = new javax.swing.JComboBox<>();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSpinner_HoursDuration = new javax.swing.JSpinner();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSpinner_MinimunQuote = new javax.swing.JSpinner();
        jSeparator16 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSpinner_Credits = new javax.swing.JSpinner();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_ID_Level = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel_IDLevel = new javax.swing.JLabel();
        jLabel_TotalLavelCredits = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSpinner_ReprobingAbsence = new javax.swing.JSpinner();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jComboBox_TypeOfCurrency = new javax.swing.JComboBox<>();
        jSeparator26 = new javax.swing.JSeparator();
        jCheckBox_ApplyScholarshipDiscounts = new javax.swing.JCheckBox();
        jCheckBox_ProfessionalPractice = new javax.swing.JCheckBox();
        jCheckBox_DegreeTest = new javax.swing.JCheckBox();
        jCheckBox_AppliesUVirtualRetirement = new javax.swing.JCheckBox();
        jLabel_TotalSubjectCredits = new javax.swing.JLabel();
        jLabel_Code1 = new javax.swing.JLabel();
        jLabel_Code2 = new javax.swing.JLabel();
        jLabel_Profile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Sidebar.setBackground(new java.awt.Color(29, 34, 39));
        jPanel_Sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseDragged(evt);
            }
        });
        jPanel_Sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseReleased(evt);
            }
        });

        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/left_15px.png"))); // NOI18N
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ASIGNATURA");

        javax.swing.GroupLayout jPanel_SidebarLayout = new javax.swing.GroupLayout(jPanel_Sidebar);
        jPanel_Sidebar.setLayout(jPanel_SidebarLayout);
        jPanel_SidebarLayout.setHorizontalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addGap(311, 311, 311)
                .addComponent(jLabel1)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel_SidebarLayout.setVerticalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_Code.setText("Code");

        jButton_Save.setBackground(new java.awt.Color(214, 61, 92));
        jButton_Save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Save.setText("Guardar");
        jButton_Save.setToolTipText("");
        jButton_Save.setBorder(null);
        jButton_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Save.setFocusable(false);
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jTabbedPane3.setBackground(new java.awt.Color(240, 240, 240));
        jTabbedPane3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(119, 123, 125));
        jLabel6.setText("ID");

        jTextField_IDSubject.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_IDSubject.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_IDSubject.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_IDSubject.setBorder(null);
        jTextField_IDSubject.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_IDSubject.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDSubjectKeyTyped(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(26, 97, 186));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(119, 123, 125));
        jLabel20.setText("ESTADO");

        jComboBox_Status.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_Status.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_Status.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Inhabilitado" }));

        jSeparator19.setBackground(new java.awt.Color(26, 97, 186));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(119, 123, 125));
        jLabel13.setText("NOTA MIN. EXTRAOR.");

        jSpinner_ExtraordinayMinimunNote.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jSpinner_ExtraordinayMinimunNote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner_ExtraordinayMinimunNoteKeyTyped(evt);
            }
        });

        jSeparator12.setBackground(new java.awt.Color(26, 97, 186));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(119, 123, 125));
        jLabel11.setText("NOTA MÍNIMA");

        jSpinner_MinimunNote.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jSpinner_MinimunNote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner_MinimunNoteKeyTyped(evt);
            }
        });

        jSeparator10.setBackground(new java.awt.Color(26, 97, 186));

        jSeparator23.setBackground(new java.awt.Color(26, 97, 186));

        jDateChooser_OpeningDate.setBackground(new java.awt.Color(240, 240, 240));
        jDateChooser_OpeningDate.setForeground(new java.awt.Color(105, 105, 105));
        jDateChooser_OpeningDate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(119, 123, 125));
        jLabel24.setText("APERTURA");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(119, 123, 125));
        jLabel7.setText("DESCRIPCIÓN");

        jTextField_Description.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_Description.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_Description.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_Description.setBorder(null);
        jTextField_Description.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_Description.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_DescriptionKeyTyped(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(26, 97, 186));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(119, 123, 125));
        jLabel12.setText("PERÍODO");

        jComboBox_Period.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_Period.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_Period.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_Period.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensual", "Bimensual", "Trimestral", "Cuatrimestral", "Quintomestral", "Semestral", "Anual" }));

        jSeparator11.setBackground(new java.awt.Color(26, 97, 186));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(119, 123, 125));
        jLabel16.setText("HRS. DE DURACIÓN");

        jSpinner_HoursDuration.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jSpinner_HoursDuration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner_HoursDurationKeyTyped(evt);
            }
        });

        jSeparator15.setBackground(new java.awt.Color(26, 97, 186));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(119, 123, 125));
        jLabel17.setText("CUPO MIN.");

        jSpinner_MinimunQuote.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jSpinner_MinimunQuote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner_MinimunQuoteKeyTyped(evt);
            }
        });

        jSeparator16.setBackground(new java.awt.Color(26, 97, 186));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSpinner_ExtraordinayMinimunNote, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_IDSubject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addComponent(jComboBox_Status, javax.swing.GroupLayout.Alignment.LEADING, 0, 174, Short.MAX_VALUE)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel13))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jLabel24)
                            .addComponent(jDateChooser_OpeningDate, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jSeparator23)
                            .addComponent(jSpinner_MinimunNote)
                            .addComponent(jSeparator10)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_Period, 0, 164, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jSpinner_HoursDuration, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jSeparator15, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jSpinner_MinimunQuote)
                    .addComponent(jSeparator16))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSpinner_MinimunQuote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser_OpeningDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_IDSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(0, 0, 0)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jSpinner_MinimunNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox_Period, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20)
                                        .addGap(16, 16, 16)
                                        .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinner_HoursDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinner_ExtraordinayMinimunNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel17)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Pág 1", jPanel3);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(119, 123, 125));
        jLabel10.setText("CRÉDITOS");

        jSpinner_Credits.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jSpinner_Credits.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_CreditsStateChanged(evt);
            }
        });
        jSpinner_Credits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner_CreditsKeyTyped(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(26, 97, 186));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(119, 123, 125));
        jLabel8.setText("NIVEL");

        jComboBox_ID_Level.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_ID_Level.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_ID_Level.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_ID_Level.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ID_LevelItemStateChanged(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(26, 97, 186));

        jLabel_IDLevel.setForeground(new java.awt.Color(105, 105, 105));
        jLabel_IDLevel.setText("ID");

        jLabel_TotalLavelCredits.setForeground(new java.awt.Color(105, 105, 105));
        jLabel_TotalLavelCredits.setText("TotalLavelCredits");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(119, 123, 125));
        jLabel18.setText("REPROBAR POR AUSENCIAS");

        jSpinner_ReprobingAbsence.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jSpinner_ReprobingAbsence.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner_ReprobingAbsenceKeyTyped(evt);
            }
        });

        jSeparator17.setBackground(new java.awt.Color(26, 97, 186));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(119, 123, 125));
        jLabel27.setText("TIPO MONEDA");

        jComboBox_TypeOfCurrency.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_TypeOfCurrency.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_TypeOfCurrency.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_TypeOfCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cordoba_Nicaraguense", "Dolar_Estadounidense", "Dolar_Beliceño", "Colon_Costarricense", "Lempira_Hondureño" }));

        jSeparator26.setBackground(new java.awt.Color(26, 97, 186));

        jCheckBox_ApplyScholarshipDiscounts.setBackground(new java.awt.Color(240, 240, 240));
        jCheckBox_ApplyScholarshipDiscounts.setForeground(new java.awt.Color(105, 105, 105));
        jCheckBox_ApplyScholarshipDiscounts.setText("Aplica Beca - Descuentos");
        jCheckBox_ApplyScholarshipDiscounts.setToolTipText("No have enphatic.");
        jCheckBox_ApplyScholarshipDiscounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_ApplyScholarshipDiscountsMouseClicked(evt);
            }
        });

        jCheckBox_ProfessionalPractice.setBackground(new java.awt.Color(240, 240, 240));
        jCheckBox_ProfessionalPractice.setForeground(new java.awt.Color(105, 105, 105));
        jCheckBox_ProfessionalPractice.setText("Práctica Profesional");
        jCheckBox_ProfessionalPractice.setToolTipText("No have enphatic.");
        jCheckBox_ProfessionalPractice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_ProfessionalPracticeMouseClicked(evt);
            }
        });

        jCheckBox_DegreeTest.setBackground(new java.awt.Color(240, 240, 240));
        jCheckBox_DegreeTest.setForeground(new java.awt.Color(105, 105, 105));
        jCheckBox_DegreeTest.setText("Prueba de Grado");
        jCheckBox_DegreeTest.setToolTipText("No have enphatic.");
        jCheckBox_DegreeTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_DegreeTestMouseClicked(evt);
            }
        });

        jCheckBox_AppliesUVirtualRetirement.setBackground(new java.awt.Color(240, 240, 240));
        jCheckBox_AppliesUVirtualRetirement.setForeground(new java.awt.Color(105, 105, 105));
        jCheckBox_AppliesUVirtualRetirement.setText("Aplica Retiro Uvirtual");
        jCheckBox_AppliesUVirtualRetirement.setToolTipText("No have enphatic.");
        jCheckBox_AppliesUVirtualRetirement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_AppliesUVirtualRetirementMouseClicked(evt);
            }
        });

        jLabel_TotalSubjectCredits.setForeground(new java.awt.Color(105, 105, 105));
        jLabel_TotalSubjectCredits.setText("TotalSubjectCredits");

        jLabel_Code1.setText("Créditos del Nivel:");

        jLabel_Code2.setText("Créd. Asig:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator9)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jSpinner_ReprobingAbsence)
                                                .addComponent(jSeparator17, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addComponent(jSpinner_Credits))
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator26)
                                        .addComponent(jComboBox_TypeOfCurrency, 0, 218, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_ApplyScholarshipDiscounts)
                                    .addComponent(jCheckBox_DegreeTest))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_AppliesUVirtualRetirement)
                                    .addComponent(jCheckBox_ProfessionalPractice))
                                .addGap(28, 28, 28))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_IDLevel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_Code1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_TotalLavelCredits)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Code2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_TotalSubjectCredits))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_ID_Level, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner_Credits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(37, 37, 37))
                            .addComponent(jComboBox_TypeOfCurrency, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner_ReprobingAbsence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_ApplyScholarshipDiscounts)
                            .addComponent(jCheckBox_ProfessionalPractice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_DegreeTest)
                            .addComponent(jCheckBox_AppliesUVirtualRetirement))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_ID_Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IDLevel)
                    .addComponent(jLabel_TotalLavelCredits)
                    .addComponent(jLabel_TotalSubjectCredits)
                    .addComponent(jLabel_Code1)
                    .addComponent(jLabel_Code2))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Pág 2", jPanel2);

        jLabel_Profile.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel_Profile.setForeground(new java.awt.Color(202, 202, 202));
        jLabel_Profile.setText("Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Code)
                        .addGap(219, 219, 219)
                        .addComponent(jLabel_Profile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTabbedPane3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Code)
                            .addComponent(jLabel_Profile))))
                .addGap(108, 108, 108))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 710, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        // TODO add your handling code here:
        JFManageSubject viewR = new JFManageSubject();

        //Mostrar vista Principal
        viewR.setLocationRelativeTo(null);
        //Guardar datos en variables
        viewR.jLabel_Code.setText(this.jLabel_Code.getText());
        viewR.jLabel_Profile.setText(this.jLabel_Profile.getText());
        this.dispose();
        viewR.setVisible(true);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    int xy, xx;
    private void jPanel_SidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel_SidebarMouseDragged

    private void jPanel_SidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel_SidebarMousePressed

    private void jPanel_SidebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_jPanel_SidebarMouseReleased

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:

        if (!"".equals(jTextField_IDSubject.getText()))
        {
            if (!"".equals(jTextField_Description.getText()))
            {
                if (jDateChooser_OpeningDate.getCalendar() != null)
                {
                    String IDSubject = jTextField_IDSubject.getText();
                    String Complement = "SUBJ_"+IDSubject;
                    String Status = jComboBox_Status.getSelectedItem().toString();
                    String Description = jTextField_Description.getText();

                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    String OpeningDate = dateFormat.format(jDateChooser_OpeningDate.getDate());

                    int Credits = Integer.parseInt(this.jSpinner_Credits.getValue().toString());
                    int MinimunNote = Integer.parseInt(this.jSpinner_MinimunNote.getValue().toString());
                    String Period = jComboBox_Period.getSelectedItem().toString();
                    int HoursDuration = Integer.parseInt(this.jSpinner_HoursDuration.getValue().toString());
                    int ExtraordinayMinimunNote = Integer.parseInt(this.jSpinner_ExtraordinayMinimunNote.getValue().toString());
                    int MinimunQuote = Integer.parseInt(this.jSpinner_MinimunQuote.getValue().toString());
                    String TypeOfCurrency = jComboBox_TypeOfCurrency.getSelectedItem().toString();
                    int ReprobingAbsence = Integer.parseInt(this.jSpinner_ReprobingAbsence.getValue().toString());
                   
                    //String CIFType = jComboBox_CIFType.getSelectedItem().toString();
                    LB_Level ObjLlevel =  (LB_Level) this.jComboBox_ID_Level.getSelectedItem();
                    String IDLevel = ObjLlevel.getID_Level();

                    if (Actualizar == true)
                    {
                        //UPDATE

                        LB = new LB_Subject(ID, IDLevel, OpeningDate, Status, Description, 
                                Credits, MinimunNote, MinimunQuote, TypeOfCurrency, 
                                Period, ReprobingAbsence, HoursDuration, ExtraordinayMinimunNote, 
                                ApplyScholarshipDiscounts, DegreeTest, ProfessionalPractice,
                                AppliesUVirtualRetirement);

                        Response = LB.Update();
                        if (LB.eye > 0)
                        {
                            JOptionPane.showMessageDialog(null, "Subject " + LB.getID_Subject()+ "\n" + Response, "AA Control - Subject", JOptionPane.INFORMATION_MESSAGE);
                            //listar
                            //this.dispose();
                        }
                        Actualizar = false;
                    }
                    else
                    {
                        //SAVE

                        LB = new LB_Subject(Complement, IDLevel, OpeningDate, Status, Description, 
                                Credits, MinimunNote, MinimunQuote, TypeOfCurrency, 
                                Period, ReprobingAbsence, HoursDuration, ExtraordinayMinimunNote, 
                                ApplyScholarshipDiscounts, DegreeTest, ProfessionalPractice,
                                AppliesUVirtualRetirement);

                        //Insert CIF
                        String rptaRegistro = LB.Insert();

                        if (rptaRegistro != null)
                        {
                            JOptionPane.showMessageDialog(null, "Subject " + IDSubject + "\n" + rptaRegistro, "AA Control - Subject", JOptionPane.INFORMATION_MESSAGE);
                            //listar
                            //this.dispose();
                        }
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "The OpeningDate Is Required !", "AA Control - Subject", JOptionPane.WARNING_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "The Description Is Required !", "AA Control - Subject", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "The ID Is Required !", "AA Control - Subject", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jTextField_IDSubjectKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDSubjectKeyTyped
        // TODO add your handling code here:
        LBKE.NumbersAndCharactersMayus(evt);
    }//GEN-LAST:event_jTextField_IDSubjectKeyTyped

    private void jTextField_DescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DescriptionKeyTyped
        // TODO add your handling code here:
        LBKE.NumbersAndCharactersMinAndCharactersMayus(evt);
    }//GEN-LAST:event_jTextField_DescriptionKeyTyped

    private void jComboBox_ID_LevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ID_LevelItemStateChanged
        // TODO add your handling code here:
        GetDataLevel();
    }//GEN-LAST:event_jComboBox_ID_LevelItemStateChanged

    private void jCheckBox_ApplyScholarshipDiscountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_ApplyScholarshipDiscountsMouseClicked
        // TODO add your handling code here:
        if (jCheckBox_ApplyScholarshipDiscounts.isSelected())
        {
            ApplyScholarshipDiscounts = 1;
        }
        else
        {
            ApplyScholarshipDiscounts = 0;
        }
    }//GEN-LAST:event_jCheckBox_ApplyScholarshipDiscountsMouseClicked

    private void jCheckBox_ProfessionalPracticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_ProfessionalPracticeMouseClicked
        // TODO add your handling code here:
        if (jCheckBox_ProfessionalPractice.isSelected())
        {
            ProfessionalPractice = 1;
        }
        else
        {
            ProfessionalPractice = 0;
        }
    }//GEN-LAST:event_jCheckBox_ProfessionalPracticeMouseClicked

    private void jCheckBox_DegreeTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_DegreeTestMouseClicked
        // TODO add your handling code here:
        if (jCheckBox_DegreeTest.isSelected())
        {
            DegreeTest = 1;
        }
        else
        {
            DegreeTest = 0;
        }
    }//GEN-LAST:event_jCheckBox_DegreeTestMouseClicked

    private void jCheckBox_AppliesUVirtualRetirementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_AppliesUVirtualRetirementMouseClicked
        // TODO add your handling code here:
        if (jCheckBox_AppliesUVirtualRetirement.isSelected())
        {
            AppliesUVirtualRetirement = 1;
        }
        else
        {
            AppliesUVirtualRetirement = 0;
        }
    }//GEN-LAST:event_jCheckBox_AppliesUVirtualRetirementMouseClicked

    private void jSpinner_CreditsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_CreditsStateChanged
        // TODO add your handling code here:
        CalcCredits();
    }//GEN-LAST:event_jSpinner_CreditsStateChanged

    private void jSpinner_ExtraordinayMinimunNoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner_ExtraordinayMinimunNoteKeyTyped
        // TODO add your handling code here:
        LBKE.Numbers(evt);
    }//GEN-LAST:event_jSpinner_ExtraordinayMinimunNoteKeyTyped

    private void jSpinner_MinimunNoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner_MinimunNoteKeyTyped
        // TODO add your handling code here:
        LBKE.Numbers(evt);
    }//GEN-LAST:event_jSpinner_MinimunNoteKeyTyped

    private void jSpinner_HoursDurationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner_HoursDurationKeyTyped
        // TODO add your handling code here:
        LBKE.Numbers(evt);
    }//GEN-LAST:event_jSpinner_HoursDurationKeyTyped

    private void jSpinner_MinimunQuoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner_MinimunQuoteKeyTyped
        // TODO add your handling code here:
        LBKE.Numbers(evt);
    }//GEN-LAST:event_jSpinner_MinimunQuoteKeyTyped

    private void jSpinner_CreditsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner_CreditsKeyTyped
        // TODO add your handling code here:
        LBKE.Numbers(evt);
    }//GEN-LAST:event_jSpinner_CreditsKeyTyped

    private void jSpinner_ReprobingAbsenceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner_ReprobingAbsenceKeyTyped
        // TODO add your handling code here:
        LBKE.Numbers(evt);
    }//GEN-LAST:event_jSpinner_ReprobingAbsenceKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDSubject dialog = new JDSubject(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Save;
    private javax.swing.JCheckBox jCheckBox_AppliesUVirtualRetirement;
    private javax.swing.JCheckBox jCheckBox_ApplyScholarshipDiscounts;
    private javax.swing.JCheckBox jCheckBox_DegreeTest;
    private javax.swing.JCheckBox jCheckBox_ProfessionalPractice;
    private javax.swing.JComboBox<String> jComboBox_ID_Level;
    private javax.swing.JComboBox<String> jComboBox_Period;
    private javax.swing.JComboBox<String> jComboBox_Status;
    public javax.swing.JComboBox<String> jComboBox_TypeOfCurrency;
    public com.toedter.calendar.JDateChooser jDateChooser_OpeningDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Close;
    public javax.swing.JLabel jLabel_Code;
    public javax.swing.JLabel jLabel_Code1;
    public javax.swing.JLabel jLabel_Code2;
    private javax.swing.JLabel jLabel_IDLevel;
    public javax.swing.JLabel jLabel_Profile;
    private javax.swing.JLabel jLabel_TotalLavelCredits;
    private javax.swing.JLabel jLabel_TotalSubjectCredits;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Sidebar;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JSpinner jSpinner_Credits;
    public javax.swing.JSpinner jSpinner_ExtraordinayMinimunNote;
    public javax.swing.JSpinner jSpinner_HoursDuration;
    public javax.swing.JSpinner jSpinner_MinimunNote;
    public javax.swing.JSpinner jSpinner_MinimunQuote;
    public javax.swing.JSpinner jSpinner_ReprobingAbsence;
    private javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JTextField jTextField_Description;
    public javax.swing.JTextField jTextField_IDSubject;
    // End of variables declaration//GEN-END:variables
}
