/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layer_Presentation;

import Layer_Business.LB_BranchOffice;
import Layer_Business.LB_Canton;
import Layer_Business.LB_Country;
import Layer_Business.LB_District;
import Layer_Business.LB_KeyEvent;
import Layer_Business.LB_Person;
import Layer_Business.LB_Province;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author KGR
 */
public class JDUAD extends java.awt.Dialog {

    /**
     * Creates new form JDUAD
     */
    LB_Person LB = new LB_Person();
    
    LB_Country LBC = new LB_Country();
    LB_Province LBPC = new LB_Province();
    LB_Canton LBCT = new LB_Canton();
    LB_District LBD = new LB_District();
    
    LB_KeyEvent LBKE = new LB_KeyEvent();
    public Boolean Actualizar = false;
    String Response;
    public String ID;
    LB_BranchOffice LBBO = new LB_BranchOffice();
    
    public JDUAD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        ListCountry();
        ListBranchOffice();
    }
    
    public void ListBranchOffice()
    {
        try 
        {
            LBBO.ListBranchOfficeCBO(this.jComboBox_BranchOffice);
        }
        catch (Exception ex) 
        {
            System.out.println(ex.getMessage());
        }
        
    }
     
    public void GetDataBranchOffice()
    {
        LB_BranchOffice Office =  (LB_BranchOffice) this.jComboBox_BranchOffice.getSelectedItem();
        String idO = Office.getID_BranchOffice();
        this.jLabel_BranchOffice.setText(idO);
    }
    
    public void ListCountry()
    {
        try 
        {
            LBC.ListCountry(this.jComboBox_CountryPeron);
        }
        catch (Exception ex) 
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void GetDataCountry()
    {
        LB_Country country =  (LB_Country) this.jComboBox_CountryPeron.getSelectedItem();
        String idC = country.getID_Country();
        this.jLabel_Country.setText(idC);
        
        /*PROVINCE*/
        LBPC.setID_Country(idC);
        LBPC.ListProvince(jComboBox_ProvincePerson);
    }
    
    public void GetDataProvince()
    {
        LB_Province province =  (LB_Province) this.jComboBox_ProvincePerson.getSelectedItem();
        String idP = province.getID_Province();
        this.jLabel_Province.setText(idP);
      
        /*DISTRICT*/
        LBD.setID_Province(idP);
        LBD.ListDistrict(jComboBox_DistrictPerson);
    }
    
    
    public void GetDataDistrict()
    {
        LB_District district =  (LB_District) this.jComboBox_DistrictPerson.getSelectedItem();
        String idDT = district.getID_District();
        this.jLabel_District.setText(idDT);
        
        /*CANTON*/
        LBCT.setID_District(idDT);
        LBCT.ListCanton(jComboBox_CantonPerson);
        
    }
    
    public void GetDataCanton()
    {
        LB_Canton canton =  (LB_Canton) this.jComboBox_CantonPerson.getSelectedItem();
        String idCT = canton.getID_Canton();
        this.jLabel_Canton.setText(idCT);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Sidebar = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Code = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_EmailPerson = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextField_NamePerson = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextField_SurnamePerson = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jTextField_LastnamePerson = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jTextField_IdentificationPerson = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jComboBox_StatePerson = new javax.swing.JComboBox<>();
        jSeparator29 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_GenderPerson = new javax.swing.JComboBox<>();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jDateChooser_BirthdayPerson = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        jComboBox_CountryPeron = new javax.swing.JComboBox<>();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jComboBox_IdentificationTypePerson = new javax.swing.JComboBox<>();
        jLabel_Country = new javax.swing.JLabel();
        jComboBox_ProvincePerson = new javax.swing.JComboBox<>();
        jLabel_Province = new javax.swing.JLabel();
        jButton_GeoLocation = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jComboBox_DistrictPerson = new javax.swing.JComboBox<>();
        jLabel_District = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jComboBox_CivilStatusPerson = new javax.swing.JComboBox<>();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jTextField_CellPhonePerson = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jTextField_HomeAddressPerson = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jComboBox_CantonPerson = new javax.swing.JComboBox<>();
        jLabel_Canton = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jComboBox_BranchOffice = new javax.swing.JComboBox<>();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel_BranchOffice = new javax.swing.JLabel();
        jButton_SignIn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel_Profile = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Sidebar.setBackground(new java.awt.Color(29, 34, 39));
        jPanel_Sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseDragged(evt);
            }
        });
        jPanel_Sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseReleased(evt);
            }
        });

        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/left_15px.png"))); // NOI18N
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EXPEDIENTE PERSONAL (UAD) ");

        javax.swing.GroupLayout jPanel_SidebarLayout = new javax.swing.GroupLayout(jPanel_Sidebar);
        jPanel_Sidebar.setLayout(jPanel_SidebarLayout);
        jPanel_SidebarLayout.setHorizontalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addGap(246, 246, 246)
                .addComponent(jLabel1)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel_SidebarLayout.setVerticalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_Close)))
                .addGap(18, 18, 18))
        );

        add(jPanel_Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 40));

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_Code.setText("Code");

        jTabbedPane3.setBackground(new java.awt.Color(240, 240, 240));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(119, 123, 125));
        jLabel2.setText("USUARIO - EMAIL");

        jTextField_EmailPerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_EmailPerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_EmailPerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_EmailPerson.setBorder(null);
        jTextField_EmailPerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_EmailPerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_EmailPersonKeyTyped(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(38, 45, 53));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(119, 123, 125));
        jLabel6.setText("NOMBRE");

        jTextField_NamePerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_NamePerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_NamePerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_NamePerson.setBorder(null);
        jTextField_NamePerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_NamePerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NamePersonKeyTyped(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(38, 45, 53));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(119, 123, 125));
        jLabel7.setText("PRIMER APELLIDO");

        jTextField_SurnamePerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_SurnamePerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_SurnamePerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_SurnamePerson.setBorder(null);
        jTextField_SurnamePerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_SurnamePerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_SurnamePersonKeyTyped(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(38, 45, 53));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(119, 123, 125));
        jLabel24.setText("SEGUNDO APELLIDO");

        jTextField_LastnamePerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_LastnamePerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_LastnamePerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_LastnamePerson.setBorder(null);
        jTextField_LastnamePerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_LastnamePerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_LastnamePersonKeyTyped(evt);
            }
        });

        jSeparator23.setBackground(new java.awt.Color(38, 45, 53));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(119, 123, 125));
        jLabel31.setText("IDENTIFICACIÓN");

        jTextField_IdentificationPerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_IdentificationPerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_IdentificationPerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_IdentificationPerson.setBorder(null);
        jTextField_IdentificationPerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_IdentificationPerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IdentificationPersonKeyTyped(evt);
            }
        });

        jSeparator30.setBackground(new java.awt.Color(38, 45, 53));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(119, 123, 125));
        jLabel30.setText("ESTADO");

        jComboBox_StatePerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_StatePerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_StatePerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_StatePerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Inhabilitado" }));

        jSeparator29.setBackground(new java.awt.Color(38, 45, 53));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox_StatePerson, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addComponent(jTextField_EmailPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31)
                        .addComponent(jLabel30)
                        .addComponent(jTextField_IdentificationPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator30))
                    .addComponent(jSeparator29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator5)
                        .addComponent(jTextField_NamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator6)
                        .addComponent(jTextField_SurnamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_LastnamePerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_EmailPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_NamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(4, 4, 4)
                                        .addComponent(jComboBox_StatePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_SurnamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_IdentificationPerson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(36, 36, 36)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator30, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_LastnamePerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Pág 1", jPanel3);

        jPanel4.setBackground(new java.awt.Color(240, 240, 240));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(119, 123, 125));
        jLabel10.setText("TIPO IDENTIFICACIÓN");

        jSeparator9.setBackground(new java.awt.Color(38, 45, 53));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(119, 123, 125));
        jLabel11.setText("GÉNERO");

        jComboBox_GenderPerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_GenderPerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_GenderPerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_GenderPerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));

        jSeparator10.setBackground(new java.awt.Color(38, 45, 53));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(119, 123, 125));
        jLabel12.setText("FECHA CUMPLEAÑOS");

        jSeparator11.setBackground(new java.awt.Color(38, 45, 53));

        jDateChooser_BirthdayPerson.setBackground(new java.awt.Color(240, 240, 240));
        jDateChooser_BirthdayPerson.setForeground(new java.awt.Color(255, 255, 255));
        jDateChooser_BirthdayPerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(119, 123, 125));
        jLabel25.setText("PAIS");

        jComboBox_CountryPeron.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_CountryPeron.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_CountryPeron.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_CountryPeron.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_CountryPeronItemStateChanged(evt);
            }
        });

        jSeparator24.setBackground(new java.awt.Color(38, 45, 53));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(119, 123, 125));
        jLabel20.setText("PROVINCIA");

        jSeparator19.setBackground(new java.awt.Color(38, 45, 53));

        jSeparator26.setBackground(new java.awt.Color(38, 45, 53));

        jComboBox_IdentificationTypePerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_IdentificationTypePerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_IdentificationTypePerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_IdentificationTypePerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula", "Pasaporte", "Carné Residencia" }));

        jLabel_Country.setText("ID");

        jComboBox_ProvincePerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_ProvincePerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_ProvincePerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_ProvincePerson.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ProvincePersonItemStateChanged(evt);
            }
        });

        jLabel_Province.setText("ID");

        jButton_GeoLocation.setText("?");
        jButton_GeoLocation.setToolTipText("The Geo-Location Parameters do not appear in the list?");
        jButton_GeoLocation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(119, 123, 125));
        jLabel19.setText("DISTRITO");

        jComboBox_DistrictPerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_DistrictPerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_DistrictPerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_DistrictPerson.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_DistrictPersonItemStateChanged(evt);
            }
        });

        jLabel_District.setText("ID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_Country, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator24, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_CountryPeron, javax.swing.GroupLayout.Alignment.LEADING, 0, 215, Short.MAX_VALUE)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_GenderPerson, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_IdentificationTypePerson, javax.swing.GroupLayout.Alignment.LEADING, 0, 216, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton_GeoLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jComboBox_DistrictPerson, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_District)
                                    .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_BirthdayPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator19)
                                .addComponent(jComboBox_ProvincePerson, 0, 200, Short.MAX_VALUE))
                            .addComponent(jLabel_Province))
                        .addGap(31, 31, 31))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_IdentificationTypePerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_GenderPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Country)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_BirthdayPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jComboBox_ProvincePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Province)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_DistrictPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox_CountryPeron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_GeoLocation))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_District)
                        .addGap(19, 19, 19))))
        );

        jTabbedPane3.addTab("Pág 2", jPanel4);

        jPanel5.setBackground(new java.awt.Color(240, 240, 240));

        jSeparator16.setBackground(new java.awt.Color(38, 45, 53));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(119, 123, 125));
        jLabel18.setText("ESTADO CIVIL");

        jComboBox_CivilStatusPerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_CivilStatusPerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_CivilStatusPerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_CivilStatusPerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado", "Viudo", "Separacion", "Union_Libre", "Otro", " " }));

        jSeparator17.setBackground(new java.awt.Color(38, 45, 53));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(119, 123, 125));
        jLabel26.setText("TELÉFONO MÓVIL");

        jTextField_CellPhonePerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_CellPhonePerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_CellPhonePerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_CellPhonePerson.setBorder(null);
        jTextField_CellPhonePerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_CellPhonePerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CellPhonePersonKeyTyped(evt);
            }
        });

        jSeparator25.setBackground(new java.awt.Color(38, 45, 53));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(119, 123, 125));
        jLabel28.setText("DIRECCIÓN CASA");

        jTextField_HomeAddressPerson.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_HomeAddressPerson.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_HomeAddressPerson.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_HomeAddressPerson.setBorder(null);
        jTextField_HomeAddressPerson.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_HomeAddressPerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_HomeAddressPersonKeyTyped(evt);
            }
        });

        jSeparator27.setBackground(new java.awt.Color(38, 45, 53));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(119, 123, 125));
        jLabel27.setText("CANTON");

        jComboBox_CantonPerson.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_CantonPerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_CantonPerson.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_CantonPerson.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_CantonPersonItemStateChanged(evt);
            }
        });

        jLabel_Canton.setText("ID");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox_CivilStatusPerson, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_CellPhonePerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator16, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel27)
                            .addComponent(jComboBox_CantonPerson, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_HomeAddressPerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_Canton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBox_CantonPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_HomeAddressPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Canton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox_CivilStatusPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_CellPhonePerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jTabbedPane3.addTab("Pág 3", jPanel5);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(119, 123, 125));
        jLabel32.setText("SEDE/SUCURSAL");

        jComboBox_BranchOffice.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_BranchOffice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_BranchOffice.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_BranchOffice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_BranchOfficeItemStateChanged(evt);
            }
        });

        jSeparator18.setBackground(new java.awt.Color(38, 45, 53));

        jLabel_BranchOffice.setText("ID");

        jButton_SignIn.setBackground(new java.awt.Color(214, 61, 92));
        jButton_SignIn.setForeground(new java.awt.Color(255, 255, 255));
        jButton_SignIn.setText("Guardar");
        jButton_SignIn.setToolTipText("");
        jButton_SignIn.setBorder(null);
        jButton_SignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_SignIn.setFocusable(false);
        jButton_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32)
                    .addComponent(jLabel_BranchOffice)
                    .addComponent(jSeparator18)
                    .addComponent(jComboBox_BranchOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_BranchOffice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(31, 31, 31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_BranchOffice)
                .addGap(141, 141, 141)
                .addComponent(jButton_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Pág 4", jPanel2);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icono-cliente.png"))); // NOI18N

        jLabel_Profile.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel_Profile.setForeground(new java.awt.Color(202, 202, 202));
        jLabel_Profile.setText("Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_Code)
                .addGap(218, 218, 218)
                .addComponent(jLabel_Profile)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Code)
                    .addComponent(jLabel_Profile)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 740, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        // TODO add your handling code here:
        JFManageUAD viewR = new JFManageUAD();

        //Mostrar vista Principal
        viewR.setLocationRelativeTo(null);
        //Guardar datos en variables
        viewR.jLabel_Code.setText(this.jLabel_Code.getText());
        viewR.jLabel_Profile.setText(this.jLabel_Profile.getText());
        this.dispose();
        viewR.setVisible(true);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    int xy, xx;
    private void jPanel_SidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel_SidebarMouseDragged

    private void jPanel_SidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel_SidebarMousePressed

    private void jPanel_SidebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_jPanel_SidebarMouseReleased

    private void jButton_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SignInActionPerformed
        // TODO add your handling code here:

        if (!jTextField_EmailPerson.getText().isEmpty())
        {
            if (!jTextField_NamePerson.getText().isEmpty())
            {
                if (!jTextField_SurnamePerson.getText().isEmpty())
                {
                    if (!jTextField_LastnamePerson.getText().isEmpty())
                    {
                        if (!jTextField_IdentificationPerson.getText().isEmpty())
                        {
                            if (jDateChooser_BirthdayPerson.getCalendar() != null)
                            {
                                if (jComboBox_ProvincePerson.getSelectedIndex() >= 0)
                                {
                                    if (jComboBox_CantonPerson.getSelectedIndex() >= 0)
                                    {
                                        if (jComboBox_DistrictPerson.getSelectedIndex() >= 0)
                                        {
                                            if (!jTextField_CellPhonePerson.getText().isEmpty())
                                            {
                                                if (!jTextField_HomeAddressPerson.getText().isEmpty())
                                                {
                                                    //String IDPerson = jTextField_IDPerson.getText();
                                                    String Name = jTextField_NamePerson.getText();
                                                    String Surname = jTextField_SurnamePerson.getText();
                                                    String Lastname = jTextField_LastnamePerson.getText();
                                                    String IdentificationType = jComboBox_IdentificationTypePerson.getSelectedItem().toString();
                                                    String Identification = jTextField_IdentificationPerson.getText();
                                                    String Gender = jComboBox_GenderPerson.getSelectedItem().toString();

                                                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                                                    String Birthday = dateFormat.format(jDateChooser_BirthdayPerson.getDate());

                                                    //String Country = jComboBox_CountryPeron.getSelectedItem().toString();
                                                    LB_Country country =  (LB_Country) this.jComboBox_CountryPeron.getSelectedItem();
                                                    String idCountry = country.getID_Country();

                                                    //String Province = jComboBox_ProvincePerson.getSelectedItem().toString();
                                                    LB_Province province =  (LB_Province) this.jComboBox_ProvincePerson.getSelectedItem();
                                                    String idProvince = province.getID_Province();

                                                    //String Canton = jComboBox_CantonPerson.getSelectedItem().toString();
                                                    LB_District district =  (LB_District) this.jComboBox_DistrictPerson.getSelectedItem();
                                                    String idDistrict = district.getID_District();

                                                    //String District = jComboBox_DistrictPerson.getSelectedItem().toString();
                                                    LB_Canton canton =  (LB_Canton) this.jComboBox_CantonPerson.getSelectedItem();
                                                    String idCanton = canton.getID_Canton();
                                                    
                                                    String CivilStatus = jComboBox_CivilStatusPerson.getSelectedItem().toString();
                                                    String CellPhone = jTextField_CellPhonePerson.getText();
                                                    String Email = jTextField_EmailPerson.getText();
                                                    String HomeAddress = jTextField_HomeAddressPerson.getText();
                                                    String State = jComboBox_StatePerson.getSelectedItem().toString();
                                                    
                                                    String complement = "PERS_"+Identification;
                                                    LB_BranchOffice Office =  (LB_BranchOffice) this.jComboBox_BranchOffice.getSelectedItem();
                                                    String idO = Office.getID_BranchOffice();

                                                    if (Actualizar == true)
                                                    {
                                                        //UPDATE
                                                        LB = new LB_Person(ID, Name, Surname, Lastname,IdentificationType, Identification,
                                                            Gender, Birthday, idCountry, idProvince, idDistrict, idCanton, idO,
                                                            CivilStatus,  CellPhone, Email, HomeAddress, State);
                                                        Response = LB.Update();
                                                        if (LB.eye > 0)
                                                        {
                                                            JOptionPane.showMessageDialog(null, "UAD " + LB.getID_Person() + "\n" + Response, "AA Control - UAD", JOptionPane.INFORMATION_MESSAGE);
                                                            //listar
                                                            //this.dispose();
                                                        }
                                                        Actualizar = false;
                                                    }
                                                    else
                                                    {
                                                        //SAVE
                                                        LB = new LB_Person(complement, Name, Surname,
                                                                    Lastname, IdentificationType, 
                                                                    Identification, Gender, Birthday,
                                                                    idCountry, idProvince, idDistrict, idCanton, idO,
                                                                    CivilStatus, CellPhone, 
                                                                    Email, HomeAddress, State);
                                                        //Insert Person
                                                        String rptaRegistro = LB.Insert();

                                                        if (rptaRegistro != null)
                                                        {
                                                            JOptionPane.showMessageDialog(null, "Person " + complement + "\n" + rptaRegistro, "AA Control - UAD", JOptionPane.INFORMATION_MESSAGE);
                                                            //listar
                                                            //this.dispose();
                                                        }
                                                    }
                                                }
                                                else
                                                {
                                                    JOptionPane.showMessageDialog(null, "The HomeAddress Is Required !", "AA Control - UAD", JOptionPane.WARNING_MESSAGE);
                                                }
                                            }
                                            else
                                            {
                                                JOptionPane.showMessageDialog(null, "The CellPhone Is Required !", "AA Control - UAD", JOptionPane.WARNING_MESSAGE);
                                            }
                                        }
                                        else
                                        {
                                            JOptionPane.showMessageDialog(null, "The District Is Required !", "AA Control - UAD", JOptionPane.WARNING_MESSAGE);
                                        }
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(null, "The Canton Is Required !", "AA Control - UAD", JOptionPane.WARNING_MESSAGE);
                                    }
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "The Province Is Required !", "AA Control - UAD", JOptionPane.WARNING_MESSAGE);
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null, "The Birthday Is Required !", "AA Control - UAD", JOptionPane.WARNING_MESSAGE);
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "The Identification Is Required !", "AA Control - UAD", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "The Lastname Is Required !", "AA Control - UAD", JOptionPane.WARNING_MESSAGE);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "The Surname Is Required !", "AA Control - UAD", JOptionPane.WARNING_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "The Name Is Required !", "AA Control - UAD", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "The User Is Required !", "AA Control - UAD", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_SignInActionPerformed

    private void jTextField_EmailPersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EmailPersonKeyTyped
        // TODO add your handling code here:
        LBKE.NumbersAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_EmailPersonKeyTyped

    private void jTextField_NamePersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NamePersonKeyTyped
        // TODO add your handling code here:
        LBKE.CharactersMayusAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_NamePersonKeyTyped

    private void jTextField_SurnamePersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SurnamePersonKeyTyped
        // TODO add your handling code here:
        LBKE.CharactersMayusAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_SurnamePersonKeyTyped

    private void jTextField_LastnamePersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_LastnamePersonKeyTyped
        // TODO add your handling code here:
        LBKE.CharactersMayusAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_LastnamePersonKeyTyped

    private void jTextField_IdentificationPersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IdentificationPersonKeyTyped
        // TODO add your handling code here:
        LBKE.NumbersAndCharactersMayus(evt);
    }//GEN-LAST:event_jTextField_IdentificationPersonKeyTyped

    private void jTextField_CellPhonePersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CellPhonePersonKeyTyped
        // TODO add your handling code here:
        LBKE.Numbers(evt);
    }//GEN-LAST:event_jTextField_CellPhonePersonKeyTyped

    private void jTextField_HomeAddressPersonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_HomeAddressPersonKeyTyped
        // TODO add your handling code here:
        LBKE.NumbersAndCharactersMinAndCharactersMayus(evt);
    }//GEN-LAST:event_jTextField_HomeAddressPersonKeyTyped

    private void jComboBox_CountryPeronItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_CountryPeronItemStateChanged
        // TODO add your handling code here:
        GetDataCountry();
    }//GEN-LAST:event_jComboBox_CountryPeronItemStateChanged

    private void jComboBox_ProvincePersonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ProvincePersonItemStateChanged
        // TODO add your handling code here:
        GetDataProvince();
    }//GEN-LAST:event_jComboBox_ProvincePersonItemStateChanged

    private void jComboBox_DistrictPersonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_DistrictPersonItemStateChanged
        // TODO add your handling code here:
        GetDataDistrict();
    }//GEN-LAST:event_jComboBox_DistrictPersonItemStateChanged

    private void jComboBox_CantonPersonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_CantonPersonItemStateChanged
        // TODO add your handling code here:
        GetDataCanton();
    }//GEN-LAST:event_jComboBox_CantonPersonItemStateChanged

    private void jComboBox_BranchOfficeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_BranchOfficeItemStateChanged
        // TODO add your handling code here:
        GetDataBranchOffice();
    }//GEN-LAST:event_jComboBox_BranchOfficeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDUAD dialog = new JDUAD(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_GeoLocation;
    public javax.swing.JButton jButton_SignIn;
    private javax.swing.JComboBox<String> jComboBox_BranchOffice;
    private javax.swing.JComboBox<String> jComboBox_CantonPerson;
    private javax.swing.JComboBox<String> jComboBox_CivilStatusPerson;
    private javax.swing.JComboBox<String> jComboBox_CountryPeron;
    private javax.swing.JComboBox<String> jComboBox_DistrictPerson;
    private javax.swing.JComboBox<String> jComboBox_GenderPerson;
    private javax.swing.JComboBox<String> jComboBox_IdentificationTypePerson;
    private javax.swing.JComboBox<String> jComboBox_ProvincePerson;
    private javax.swing.JComboBox<String> jComboBox_StatePerson;
    public com.toedter.calendar.JDateChooser jDateChooser_BirthdayPerson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_BranchOffice;
    private javax.swing.JLabel jLabel_Canton;
    private javax.swing.JLabel jLabel_Close;
    public javax.swing.JLabel jLabel_Code;
    private javax.swing.JLabel jLabel_Country;
    private javax.swing.JLabel jLabel_District;
    public javax.swing.JLabel jLabel_Profile;
    private javax.swing.JLabel jLabel_Province;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_Sidebar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JTextField jTextField_CellPhonePerson;
    public javax.swing.JTextField jTextField_EmailPerson;
    public javax.swing.JTextField jTextField_HomeAddressPerson;
    public javax.swing.JTextField jTextField_IdentificationPerson;
    public javax.swing.JTextField jTextField_LastnamePerson;
    public javax.swing.JTextField jTextField_NamePerson;
    public javax.swing.JTextField jTextField_SurnamePerson;
    // End of variables declaration//GEN-END:variables
}
